package:
  name: fipscheck-lib-amzn2-aarch64
  version: 1.4.1

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/fipscheck-lib-1.4.1-6.amzn2.0.2.aarch64.rpm
    sha256: 5ead9ff25b918f0f237ad1ac75ef39172dad62e0e8c20c3a1b8e87a0abd3122f
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/fipscheck-1.4.1-6.amzn2.0.2.src.rpm
    sha256: d3d3a7ed94ccdfccdf7b2224bc0ce03a347ef1595c31ac863a164547f27d713f
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
  host:
    - glibc-amzn2-aarch64 ==2.26
  run:
    - glibc-amzn2-aarch64 ==2.26

about:
  home: http://fedorahosted.org/fipscheck/
  license: BSD
  license_family: BSD
  summary: "(CDT) Library files for fipscheck"
  description: |
        This package contains the FIPSCheck library.

extras:
  rpm_name: fipscheck-lib
