package:
  name: libvorbis-amzn2-aarch64
  version: 1.3.3

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/libvorbis-1.3.3-8.amzn2.0.2.aarch64.rpm
    sha256: 2d1504c3f62585daeb527975d1c8ba8afc699dcee95306132d19ad7211e6c179
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/libvorbis-1.3.3-8.amzn2.0.2.src.rpm
    sha256: b153c4609e6b2b9ab0cc144d5bbbc53a56c5d33b482de9219259991b97cb7dd8
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
    - libogg-amzn2-aarch64 ==1.3.0
  host:
    - glibc-amzn2-aarch64 ==2.26
    - libogg-amzn2-aarch64 ==1.3.0
  run:
    - glibc-amzn2-aarch64 ==2.26
    - libogg-amzn2-aarch64 ==1.3.0

about:
  home: http://www.xiph.org/
  license: BSD
  license_family: BSD
  summary: "(CDT) The Vorbis General Audio Compression Codec"
  description: |
        Ogg Vorbis is a fully open, non-proprietary, patent- and royalty-free,
        general-purpose compressed audio format for audio and music at fixed and
        variable bitrates.  The libvorbis package contains runtime libraries for use
        in programs that support Ogg Vorbis.

extras:
  rpm_name: libvorbis
