package:
  name: libsigcxx20-amzn2-aarch64
  version: 2.10.0

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/libsigc%2B%2B20-2.10.0-1.amzn2.0.2.aarch64.rpm
    sha256: 367dfe39e75ab581c6177df9681d223bef262f533e1befebd58b39cde0d9e337
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/libsigc%2B%2B20-2.10.0-1.amzn2.0.2.src.rpm
    sha256: 15f55436d1e730518c72df68b926d65510560df615d2647253b51bf7264efdc3
    no_hoist: true
    folder: source

build:
  number: 3
  noarch: generic
  rpaths:
    - lib
    - lib64
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
    - libgcc-amzn2-aarch64 ==7.3.1
    - libstdcxx-amzn2-aarch64 ==7.3.1
  host:
    - glibc-amzn2-aarch64 ==2.26
    - libgcc-amzn2-aarch64 ==7.3.1
    - libstdcxx-amzn2-aarch64 ==7.3.1
  run:
    - glibc-amzn2-aarch64 ==2.26
    - libgcc-amzn2-aarch64 ==7.3.1
    - libstdcxx-amzn2-aarch64 ==7.3.1

about:
  home: http://libsigc.sourceforge.net/
  license: LGPL (>= 2)
  license_family: LGPL
  summary: "(CDT) Typesafe signal framework for C++"
  description: |
        This library implements a full callback system for use in widget libraries,
        abstract interfaces, and general programming. Originally part of the Gtk--
        widget set, libsigc++20 is now a separate library to provide for more general
        use. It is the most complete library of its kind with the ability to connect
        an abstract callback to a class method, function, or function object. It
        contains adaptor classes for connection of dissimilar callbacks and has an
        ease of use unmatched by other C++ callback libraries.  Package GTK-- (gtkmm),
        which is a C++ binding to the GTK+ library, starting with version 1.1.2, uses
        libsigc++20.

extras:
  rpm_name: libsigc++20
