package:
  name: setup-amzn2-aarch64
  version: 2.8.71

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/setup-2.8.71-10.amzn2.0.1.noarch.rpm
    sha256: 4af960919a8c867bef98df72744e313cab15658cfdb131793e8f6ad959e6b6d6
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/setup-2.8.71-10.amzn2.0.1.src.rpm
    sha256: a048edcb5e7a6552e092a3fd74a073fdd49e7269dd6f7b982088dc71a32cf631
    no_hoist: true
    folder: source

build:
  number: 3
  noarch: generic
  rpaths:
    - lib
    - lib64
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - system-release-amzn2-aarch64 ==2
  host:
    - system-release-amzn2-aarch64 ==2
  run:
    - system-release-amzn2-aarch64 ==2

about:
  home: https://pagure.io/setup/
  license: Public-Domain
  license_family: Public-Domain
  summary: "(CDT) A set of system configuration and setup files"
  description: |
        The setup package contains a set of important system configuration and setup
        files, such as passwd, group, and profile.

extras:
  rpm_name: setup
