package:
  name: nspr-amzn2-aarch64
  version: 4.25.0

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/nspr-4.25.0-2.amzn2.aarch64.rpm
    sha256: ac3a83d061d877b447bcc0b6d41be8142c34fd557a3002ef6084d08d370299f6
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/nspr-4.25.0-2.amzn2.src.rpm
    sha256: ee6e13b6baffbdfc9c535381457bd739f0ff43933507ee52375981b9e0ee12fa
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
  host:
    - glibc-amzn2-aarch64 ==2.26
  run:
    - glibc-amzn2-aarch64 ==2.26

about:
  home: http://www.mozilla.org/projects/nspr/
  license: MPLv2.0
  license_family: Other
  summary: "(CDT) Netscape Portable Runtime"
  description: |
        NSPR provides platform independence for non-GUI operating system facilities.
        These facilities include threads, thread synchronization, normal file and
        network I/O, interval timing and calendar time, basic memory management
        (malloc and free) and shared library linking.

extras:
  rpm_name: nspr
