package:
  name: mesa-libgl-amzn2-aarch64
  version: 18.3.4

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/mesa-libGL-18.3.4-5.amzn2.0.1.aarch64.rpm
    sha256: 2873760cc00466d0b08aa1a665fbefbdc28506c4882d09f296d58da7283611b3
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/mesa-18.3.4-5.amzn2.0.1.src.rpm
    sha256: 6a8b6b5fe494d93ba576820d4cfa246c67108428b877558a3fbc9c4f2fe9e8af
    no_hoist: true
    folder: source

build:
  number: 3
  noarch: generic
  rpaths:
    - lib
    - lib64
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - expat-amzn2-aarch64 ==2.1.0
    - glibc-amzn2-aarch64 ==2.26
    - libdrm-amzn2-aarch64 >=2.4.83
    - libdrm-amzn2-aarch64 ==2.4.97
    - libglvnd-glx-amzn2-aarch64 >=1.0.1
    - libselinux-amzn2-aarch64 ==2.5
    - libx11-amzn2-aarch64 ==1.6.7
    - libxcb-amzn2-aarch64 ==1.12
    - libxdamage-amzn2-aarch64 ==1.1.4
    - libxext-amzn2-aarch64 ==1.3.3
    - libxfixes-amzn2-aarch64 ==5.0.3
    - libxshmfence-amzn2-aarch64 ==1.2
    - libxxf86vm-amzn2-aarch64 ==1.1.4
    - mesa-libglapi-amzn2-aarch64 ==18.3.4
    - zlib-amzn2-aarch64 ==1.2.7
  host:
    - expat-amzn2-aarch64 ==2.1.0
    - glibc-amzn2-aarch64 ==2.26
    - libdrm-amzn2-aarch64 >=2.4.83
    - libdrm-amzn2-aarch64 ==2.4.97
    - libglvnd-glx-amzn2-aarch64 >=1.0.1
    - libselinux-amzn2-aarch64 ==2.5
    - libx11-amzn2-aarch64 ==1.6.7
    - libxcb-amzn2-aarch64 ==1.12
    - libxdamage-amzn2-aarch64 ==1.1.4
    - libxext-amzn2-aarch64 ==1.3.3
    - libxfixes-amzn2-aarch64 ==5.0.3
    - libxshmfence-amzn2-aarch64 ==1.2
    - libxxf86vm-amzn2-aarch64 ==1.1.4
    - mesa-libglapi-amzn2-aarch64 ==18.3.4
    - zlib-amzn2-aarch64 ==1.2.7
  run:
    - expat-amzn2-aarch64 ==2.1.0
    - glibc-amzn2-aarch64 ==2.26
    - libdrm-amzn2-aarch64 >=2.4.83
    - libdrm-amzn2-aarch64 ==2.4.97
    - libglvnd-glx-amzn2-aarch64 >=1.0.1
    - libselinux-amzn2-aarch64 ==2.5
    - libx11-amzn2-aarch64 ==1.6.7
    - libxcb-amzn2-aarch64 ==1.12
    - libxdamage-amzn2-aarch64 ==1.1.4
    - libxext-amzn2-aarch64 ==1.3.3
    - libxfixes-amzn2-aarch64 ==5.0.3
    - libxshmfence-amzn2-aarch64 ==1.2
    - libxxf86vm-amzn2-aarch64 ==1.1.4
    - mesa-libglapi-amzn2-aarch64 ==18.3.4
    - zlib-amzn2-aarch64 ==1.2.7

about:
  home: http://www.mesa3d.org
  license: MIT
  license_family: MIT
  summary: "(CDT) Mesa libGL runtime libraries and DRI drivers"
  description: |
        Mesa libGL runtime library.

extras:
  rpm_name: mesa-libGL
