package:
  name: libfdisk-amzn2-aarch64
  version: 2.30.2

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/libfdisk-2.30.2-2.amzn2.0.4.aarch64.rpm
    sha256: 87b19d99bb7fe305905f0f7fc64856e55839593c15ed1fc3800898543b33b0dc
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/util-linux-2.30.2-2.amzn2.0.4.src.rpm
    sha256: 7967325dfd44cdb0fd0caa45b27d56da920dd3110a5989c3ae52364b44ae7d82
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
    - libblkid-amzn2-aarch64 ==2.30.2
    - libuuid-amzn2-aarch64 ==2.30.2
  host:
    - glibc-amzn2-aarch64 ==2.26
    - libblkid-amzn2-aarch64 ==2.30.2
    - libuuid-amzn2-aarch64 ==2.30.2
  run:
    - glibc-amzn2-aarch64 ==2.26
    - libblkid-amzn2-aarch64 ==2.30.2
    - libuuid-amzn2-aarch64 ==2.30.2

about:
  home: http://en.wikipedia.org/wiki/Util-linux
  license: LGPL (>= 2)
  license_family: LGPL
  summary: "(CDT) Partitioning library for fdisk-like programs."
  description: |
        This is library for fdisk-like programs, part of util-linux.

extras:
  rpm_name: libfdisk
