package:
  name: gtk2-amzn2-aarch64
  version: 2.24.31

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/gtk2-2.24.31-1.amzn2.0.2.aarch64.rpm
    sha256: f7b67eec0bf32ce4d79e478e1964ecf8ed886d3dd6cc0a30a3ba3fec4a753c15
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/gtk2-2.24.31-1.amzn2.0.2.src.rpm
    sha256: d57404a6a9e54b6d1efcbf7fe3685fae8984f33e86b0f311002d2f8e72e94c96
    no_hoist: true
    folder: source

build:
  number: 3
  noarch: generic
  rpaths:
    - lib
    - lib64
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - atk-amzn2-aarch64 >=1.29.4
    - atk-amzn2-aarch64 ==2.22.0
    - cairo-amzn2-aarch64 ==1.15.12
    - cups-libs-amzn2-aarch64 ==1.6.3
    - fontconfig-amzn2-aarch64 ==2.13.0
    - freetype-amzn2-aarch64 ==2.8
    - gdk-pixbuf2-amzn2-aarch64 ==2.36.12
    - glib2-amzn2-aarch64 >=2.28.0
    - glib2-amzn2-aarch64 ==2.56.1
    - glibc-amzn2-aarch64 ==2.26
    - gtk-update-icon-cache-amzn2-aarch64 ==3.22.30
    - hicolor-icon-theme-amzn2-aarch64 ==0.12
    - libtiff-amzn2-aarch64 >=3.6.1
    - libx11-amzn2-aarch64 ==1.6.7
    - libxcomposite-amzn2-aarch64 ==0.4.4
    - libxcursor-amzn2-aarch64 ==1.1.15
    - libxdamage-amzn2-aarch64 ==1.1.4
    - libxext-amzn2-aarch64 ==1.3.3
    - libxfixes-amzn2-aarch64 ==5.0.3
    - libxi-amzn2-aarch64 ==1.7.9
    - libxinerama-amzn2-aarch64 ==1.1.3
    - libxrandr-amzn2-aarch64 >=1.2.99.4
    - libxrandr-amzn2-aarch64 ==1.5.1
    - libxrender-amzn2-aarch64 ==0.9.10
    - pango-amzn2-aarch64 >=1.20.0
    - pango-amzn2-aarch64 ==1.42.4
  host:
    - atk-amzn2-aarch64 >=1.29.4
    - atk-amzn2-aarch64 ==2.22.0
    - cairo-amzn2-aarch64 ==1.15.12
    - cups-libs-amzn2-aarch64 ==1.6.3
    - fontconfig-amzn2-aarch64 ==2.13.0
    - freetype-amzn2-aarch64 ==2.8
    - gdk-pixbuf2-amzn2-aarch64 ==2.36.12
    - glib2-amzn2-aarch64 >=2.28.0
    - glib2-amzn2-aarch64 ==2.56.1
    - glibc-amzn2-aarch64 ==2.26
    - gtk-update-icon-cache-amzn2-aarch64 ==3.22.30
    - hicolor-icon-theme-amzn2-aarch64 ==0.12
    - libtiff-amzn2-aarch64 >=3.6.1
    - libx11-amzn2-aarch64 ==1.6.7
    - libxcomposite-amzn2-aarch64 ==0.4.4
    - libxcursor-amzn2-aarch64 ==1.1.15
    - libxdamage-amzn2-aarch64 ==1.1.4
    - libxext-amzn2-aarch64 ==1.3.3
    - libxfixes-amzn2-aarch64 ==5.0.3
    - libxi-amzn2-aarch64 ==1.7.9
    - libxinerama-amzn2-aarch64 ==1.1.3
    - libxrandr-amzn2-aarch64 >=1.2.99.4
    - libxrandr-amzn2-aarch64 ==1.5.1
    - libxrender-amzn2-aarch64 ==0.9.10
    - pango-amzn2-aarch64 >=1.20.0
    - pango-amzn2-aarch64 ==1.42.4
  run:
    - atk-amzn2-aarch64 >=1.29.4
    - atk-amzn2-aarch64 ==2.22.0
    - cairo-amzn2-aarch64 ==1.15.12
    - cups-libs-amzn2-aarch64 ==1.6.3
    - fontconfig-amzn2-aarch64 ==2.13.0
    - freetype-amzn2-aarch64 ==2.8
    - gdk-pixbuf2-amzn2-aarch64 ==2.36.12
    - glib2-amzn2-aarch64 >=2.28.0
    - glib2-amzn2-aarch64 ==2.56.1
    - glibc-amzn2-aarch64 ==2.26
    - gtk-update-icon-cache-amzn2-aarch64 ==3.22.30
    - hicolor-icon-theme-amzn2-aarch64 ==0.12
    - libtiff-amzn2-aarch64 >=3.6.1
    - libx11-amzn2-aarch64 ==1.6.7
    - libxcomposite-amzn2-aarch64 ==0.4.4
    - libxcursor-amzn2-aarch64 ==1.1.15
    - libxdamage-amzn2-aarch64 ==1.1.4
    - libxext-amzn2-aarch64 ==1.3.3
    - libxfixes-amzn2-aarch64 ==5.0.3
    - libxi-amzn2-aarch64 ==1.7.9
    - libxinerama-amzn2-aarch64 ==1.1.3
    - libxrandr-amzn2-aarch64 >=1.2.99.4
    - libxrandr-amzn2-aarch64 ==1.5.1
    - libxrender-amzn2-aarch64 ==0.9.10
    - pango-amzn2-aarch64 >=1.20.0
    - pango-amzn2-aarch64 ==1.42.4

about:
  home: http://www.gtk.org
  license: LGPL (>= 2)
  license_family: LGPL
  summary: "(CDT) The GIMP ToolKit (GTK+), a library for creating GUIs for X"
  description: |
        GTK+ is a multi-platform toolkit for creating graphical user interfaces.
        Offering a complete set of widgets, GTK+ is suitable for projects ranging from
        small one-off tools to complete application suites.

extras:
  rpm_name: gtk2
