package:
  name: libglvnd-amzn2-aarch64
  version: 1.0.1

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/libglvnd-1.0.1-0.1.git5baa1e5.amzn2.0.1.aarch64.rpm
    sha256: c4fe6a0ac9eec64074bf004ed3d72acb2ce9670e9e6394cf37a9094ce5fcdae9
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/libglvnd-1.0.1-0.1.git5baa1e5.amzn2.0.1.src.rpm
    sha256: 8de516b03b41124fda9642b96b8bea7cf60604c31ffd82c4a6e93e9cb9b3b765
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
  host:
    - glibc-amzn2-aarch64 ==2.26
  run:
    - glibc-amzn2-aarch64 ==2.26

about:
  home: https://github.com/NVIDIA/libglvnd
  license: MIT
  license_family: MIT
  summary: "(CDT) The GL Vendor-Neutral Dispatch library"
  description: |
        libglvnd is an implementation of the vendor-neutral dispatch layer for
        arbitrating OpenGL API calls between multiple vendors on a per-screen basis.

extras:
  rpm_name: libglvnd
