package:
  name: libxext-devel-amzn2-aarch64
  version: 1.3.3

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/libXext-devel-1.3.3-3.amzn2.0.2.aarch64.rpm
    sha256: 4ac36b03a68f3420ef5419006a8b0ca116821bb46d7d0e451c9b52bd77b1cc25
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/libXext-1.3.3-3.amzn2.0.2.src.rpm
    sha256: a5b66b05599fc270d30100847fc29548116293d1bd013b60f480eb9ece7bad98
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libxext-amzn2-aarch64 ==1.3.3
  host:
    - libxext-amzn2-aarch64 ==1.3.3
  run:
    - libxext-amzn2-aarch64 ==1.3.3

about:
  home: http://www.x.org
  license: MIT
  license_family: MIT
  summary: "(CDT) X.Org X11 libXext development package"
  description: |
        X.Org X11 libXext development package

extras:
  rpm_name: libXext-devel
