package:
  name: libxcomposite-amzn2-aarch64
  version: 0.4.4

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/libXcomposite-0.4.4-4.1.amzn2.0.2.aarch64.rpm
    sha256: d2c0747d389e6c2cf26cfb5cceffe47ee30b0ea3eee088b6608637968e2b493d
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/libXcomposite-0.4.4-4.1.amzn2.0.2.src.rpm
    sha256: 3f8406d56c4417defbbe2b3bd16753d76da5ea281ffc5c745183be153e194d44
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
    - libx11-amzn2-aarch64 ==1.6.7
  host:
    - glibc-amzn2-aarch64 ==2.26
    - libx11-amzn2-aarch64 ==1.6.7
  run:
    - glibc-amzn2-aarch64 ==2.26
    - libx11-amzn2-aarch64 ==1.6.7

about:
  home: http://www.x.org
  license: MIT
  license_family: MIT
  summary: "(CDT) X Composite Extension library"
  description: |
        X Composite Extension library

extras:
  rpm_name: libXcomposite
