package:
  name: libxcb-amzn2-aarch64
  version: 1.12

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/libxcb-1.12-1.amzn2.0.2.aarch64.rpm
    sha256: 6562700b16b4657d9578fbe3e7fc9ea220703ce6d1eb747dae260294f1ab62e8
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/libxcb-1.12-1.amzn2.0.2.src.rpm
    sha256: f247c6b583421db5b27b36aa2d19d8cc44685181e32fd319cc2f6aae8d998d88
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
    - libxau-amzn2-aarch64 ==1.0.8
  host:
    - glibc-amzn2-aarch64 ==2.26
    - libxau-amzn2-aarch64 ==1.0.8
  run:
    - glibc-amzn2-aarch64 ==2.26
    - libxau-amzn2-aarch64 ==1.0.8

about:
  home: http://xcb.freedesktop.org/
  license: MIT
  license_family: MIT
  summary: "(CDT) A C binding to the X11 protocol"
  description: |
        The X protocol C-language Binding (XCB) is a replacement for Xlib featuring a
        small footprint, latency hiding, direct access to the protocol, improved
        threading support, and extensibility.

extras:
  rpm_name: libxcb
