package:
  name: shadow-utils-amzn2-aarch64
  version: 4.1.5.1

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/shadow-utils-4.1.5.1-24.amzn2.0.2.aarch64.rpm
    sha256: 770802b47fe5cc2e6bfc47a6283de4171fba4bbfaf4f14d09ac5a640e6c4c75f
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/shadow-utils-4.1.5.1-24.amzn2.0.2.src.rpm
    sha256: 67028c7c7a187acb001e6d1e6de4c5bd5b910956af664e96d50da7e4a07fed74
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - audit-libs-amzn2-aarch64 >=1.6.5
    - audit-libs-amzn2-aarch64 ==2.8.1
    - coreutils-amzn2-aarch64 ==8.22
    - glibc-amzn2-aarch64 ==2.26
    - libacl-amzn2-aarch64 ==2.2.51
    - libattr-amzn2-aarch64 ==2.4.46
    - libcrypt-amzn2-aarch64 ==2.26
    - libselinux-amzn2-aarch64 >=1.25.2
    - libselinux-amzn2-aarch64 ==2.5
    - libsemanage-amzn2-aarch64 ==2.5
    - setup-amzn2-aarch64 ==2.8.71
  host:
    - audit-libs-amzn2-aarch64 >=1.6.5
    - audit-libs-amzn2-aarch64 ==2.8.1
    - coreutils-amzn2-aarch64 ==8.22
    - glibc-amzn2-aarch64 ==2.26
    - libacl-amzn2-aarch64 ==2.2.51
    - libattr-amzn2-aarch64 ==2.4.46
    - libcrypt-amzn2-aarch64 ==2.26
    - libselinux-amzn2-aarch64 >=1.25.2
    - libselinux-amzn2-aarch64 ==2.5
    - libsemanage-amzn2-aarch64 ==2.5
    - setup-amzn2-aarch64 ==2.8.71
  run:
    - audit-libs-amzn2-aarch64 >=1.6.5
    - audit-libs-amzn2-aarch64 ==2.8.1
    - coreutils-amzn2-aarch64 ==8.22
    - glibc-amzn2-aarch64 ==2.26
    - libacl-amzn2-aarch64 ==2.2.51
    - libattr-amzn2-aarch64 ==2.4.46
    - libcrypt-amzn2-aarch64 ==2.26
    - libselinux-amzn2-aarch64 >=1.25.2
    - libselinux-amzn2-aarch64 ==2.5
    - libsemanage-amzn2-aarch64 ==2.5
    - setup-amzn2-aarch64 ==2.8.71

about:
  home: http://pkg-shadow.alioth.debian.org/
  license: BSD and GPLv2+
  license_family: GPL2
  summary: "(CDT) Utilities for managing accounts and shadow password files"
  description: |
        The shadow-utils package includes the necessary programs for converting UNIX
        password files to the shadow password format, plus programs for managing user
        and group accounts. The pwconv command converts passwords to the shadow
        password format. The pwunconv command unconverts shadow passwords and
        generates a passwd file (a standard UNIX password file). The pwck command
        checks the integrity of password and shadow files. The lastlog command prints
        out the last login times for all users. The useradd, userdel, and usermod
        commands are used for managing user accounts. The groupadd, groupdel, and
        groupmod commands are used for managing group accounts.

extras:
  rpm_name: shadow-utils
