package:
  name: gettext-amzn2-aarch64
  version: 0.19.8.1

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/gettext-0.19.8.1-3.amzn2.aarch64.rpm
    sha256: 303ceb86177fe026d8941de0a326d2ad231c6b04e4d2c0e4ba812bf14971b1c3
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/gettext-0.19.8.1-3.amzn2.src.rpm
    sha256: dcec779a471f2b55af8108d559d3c4223843cb7f793ab80ae150b45ec28e873d
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - gettext-libs-amzn2-aarch64 ==0.19.8.1
    - glib2-amzn2-aarch64 ==2.56.1
    - glibc-amzn2-aarch64 ==2.26
    - info-amzn2-aarch64 ==5.1
    - libcroco-amzn2-aarch64 ==0.6.12
    - libgcc-amzn2-aarch64 ==7.3.1
    - libgomp-amzn2-aarch64 ==7.3.1
    - libunistring-amzn2-aarch64 ==0.9.3
    - libxml2-amzn2-aarch64 ==2.9.1
    - ncurses-libs-amzn2-aarch64 ==6.0
  host:
    - gettext-libs-amzn2-aarch64 ==0.19.8.1
    - glib2-amzn2-aarch64 ==2.56.1
    - glibc-amzn2-aarch64 ==2.26
    - info-amzn2-aarch64 ==5.1
    - libcroco-amzn2-aarch64 ==0.6.12
    - libgcc-amzn2-aarch64 ==7.3.1
    - libgomp-amzn2-aarch64 ==7.3.1
    - libunistring-amzn2-aarch64 ==0.9.3
    - libxml2-amzn2-aarch64 ==2.9.1
    - ncurses-libs-amzn2-aarch64 ==6.0
  run:
    - gettext-libs-amzn2-aarch64 ==0.19.8.1
    - glib2-amzn2-aarch64 ==2.56.1
    - glibc-amzn2-aarch64 ==2.26
    - info-amzn2-aarch64 ==5.1
    - libcroco-amzn2-aarch64 ==0.6.12
    - libgcc-amzn2-aarch64 ==7.3.1
    - libgomp-amzn2-aarch64 ==7.3.1
    - libunistring-amzn2-aarch64 ==0.9.3
    - libxml2-amzn2-aarch64 ==2.9.1
    - ncurses-libs-amzn2-aarch64 ==6.0

about:
  home: http://www.gnu.org/software/gettext/
  license: GPLv3+ and LGPLv2+
  license_family: GPL3
  summary: "(CDT) GNU libraries and utilities for producing multi-lingual messages"
  description: |
        The GNU gettext package provides a set of tools and documentation for
        producing multi-lingual messages in programs. Tools include a set of
        conventions about how programs should be written to support message catalogs,
        a directory and file naming organization for the message catalogs, a runtime
        library which supports the retrieval of translated messages, and stand-alone
        programs for handling the translatable and the already translated strings.
        Gettext provides an easy to use library and tools for creating, using, and
        modifying natural language catalogs and is a powerful and simple method for
        internationalizing programs.

extras:
  rpm_name: gettext
