package:
  name: keyutils-libs-devel-amzn2-aarch64
  version: 1.5.8

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/keyutils-libs-devel-1.5.8-3.amzn2.0.2.aarch64.rpm
    sha256: a00399e7636c33ee4772b2ceff5ba5e5ddaf609a427cddaeeb9948cce0e17178
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/keyutils-1.5.8-3.amzn2.0.2.src.rpm
    sha256: 1579dc52bd90d64e68d663da4dfa4462afa9df1cfbef30d47b64add0dd12210e
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - keyutils-libs-amzn2-aarch64 ==1.5.8
  host:
    - keyutils-libs-amzn2-aarch64 ==1.5.8
  run:
    - keyutils-libs-amzn2-aarch64 ==1.5.8

about:
  home: http://people.redhat.com/~dhowells/keyutils/
  license: GPLv2+ and LGPLv2+
  license_family: GPL2
  summary: "(CDT) Development package for building Linux key management utilities"
  description: |
        This package provides headers and libraries for building key utilities.

extras:
  rpm_name: keyutils-libs-devel
