package:
  name: libsm-devel-amzn2-aarch64
  version: 1.2.2

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/libSM-devel-1.2.2-2.amzn2.0.2.aarch64.rpm
    sha256: f7422233b8797f24ea0203f676752ad4efed0ec215e78132ec21aa6f774a1e98
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/libSM-1.2.2-2.amzn2.0.2.src.rpm
    sha256: 282e50e8814f0760a3c2624f3a16250666d871524fc028aa2dce0f5d2dbd94a1
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libsm-amzn2-aarch64 ==1.2.2
  host:
    - libsm-amzn2-aarch64 ==1.2.2
  run:
    - libsm-amzn2-aarch64 ==1.2.2

about:
  home: http://www.x.org
  license: MIT
  license_family: MIT
  summary: "(CDT) X.Org X11 SM development package"
  description: |
        The X.Org X11 SM (Session Management) development package.

extras:
  rpm_name: libSM-devel
