package:
  name: pulseaudio-libs-devel-amzn2-aarch64
  version: 10.0

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/pulseaudio-libs-devel-10.0-3.amzn2.0.3.aarch64.rpm
    sha256: eb1913037223e682fafd212b47665d6517b340daa475f6f9db79d061d5ec692f
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/pulseaudio-10.0-3.amzn2.0.3.src.rpm
    sha256: 614c5717425ddbe454704382dadc7bed8aad353ea67283b9897717e10e1150c2
    no_hoist: true
    folder: source

build:
  number: 3
  noarch: generic
  rpaths:
    - lib
    - lib64
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - pulseaudio-libs-amzn2-aarch64 ==10.0
    - pulseaudio-libs-glib2-amzn2-aarch64 ==10.0
  host:
    - pulseaudio-libs-amzn2-aarch64 ==10.0
    - pulseaudio-libs-glib2-amzn2-aarch64 ==10.0
  run:
    - pulseaudio-libs-amzn2-aarch64 ==10.0
    - pulseaudio-libs-glib2-amzn2-aarch64 ==10.0

about:
  home: http://www.freedesktop.org/wiki/Software/PulseAudio
  license: LGPL (>= 2)
  license_family: LGPL
  summary: "(CDT) Headers and libraries for PulseAudio client development"
  description: |
        Headers and libraries for developing applications that can communicate with a
        PulseAudio sound server.

extras:
  rpm_name: pulseaudio-libs-devel
