package:
  name: libxrandr-devel-amzn2-aarch64
  version: 1.5.1

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/libXrandr-devel-1.5.1-2.amzn2.0.3.aarch64.rpm
    sha256: da9dacfd6d789362375d9e38acc171a733ac5437af4269f13929d3500819f322
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/libXrandr-1.5.1-2.amzn2.0.3.src.rpm
    sha256: 7ccd9af12a2893b98af29ca7c2136bd470c2e9f7fd2d9ed9430d83189baf2382
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libxrandr-amzn2-aarch64 ==1.5.1
  host:
    - libxrandr-amzn2-aarch64 ==1.5.1
  run:
    - libxrandr-amzn2-aarch64 ==1.5.1

about:
  home: http://www.x.org
  license: MIT
  license_family: MIT
  summary: "(CDT) X.Org X11 libXrandr development package"
  description: |
        X.Org X11 libXrandr development package

extras:
  rpm_name: libXrandr-devel
