package:
  name: libxi-amzn2-aarch64
  version: 1.7.9

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/libXi-1.7.9-1.amzn2.0.2.aarch64.rpm
    sha256: b39654f2d3d331530acb44df571d3e854e9f24648224e7457d42af5914c84f95
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/libXi-1.7.9-1.amzn2.0.2.src.rpm
    sha256: 686eb0dd38a1cbb515f348a0204fb5ec98696b72d2570463433fa97096a8a168
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
    - libx11-amzn2-aarch64 >=1.5.99.902
    - libx11-amzn2-aarch64 ==1.6.7
    - libxext-amzn2-aarch64 ==1.3.3
  host:
    - glibc-amzn2-aarch64 ==2.26
    - libx11-amzn2-aarch64 >=1.5.99.902
    - libx11-amzn2-aarch64 ==1.6.7
    - libxext-amzn2-aarch64 ==1.3.3
  run:
    - glibc-amzn2-aarch64 ==2.26
    - libx11-amzn2-aarch64 >=1.5.99.902
    - libx11-amzn2-aarch64 ==1.6.7
    - libxext-amzn2-aarch64 ==1.3.3

about:
  home: http://www.x.org
  license: MIT
  license_family: MIT
  summary: "(CDT) X.Org X11 libXi runtime library"
  description: |
        X.Org X11 libXi runtime library

extras:
  rpm_name: libXi
