package:
  name: kernel-headers-amzn2-aarch64
  version: 4.14.214

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/kernel-headers-4.14.214-160.339.amzn2.aarch64.rpm
    sha256: 6dc942a32dae8a2a4579de2140741a8caaa7bbbac04e83f0b1226bb9ca909e91
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/kernel-4.14.214-160.339.amzn2.src.rpm
    sha256: 885054635a0ddb689065536630e6b877c731512ad9b6a438e5508f09d0f1447b
    no_hoist: true
    folder: source

build:
  number: 3
  noarch: generic
  rpaths:
    - lib
    - lib64
  missing_dso_whitelist:
    - '*'



about:
  home: http://www.kernel.org/
  license: GPLv2 and Redistributable, no modification permitted
  license_family: GPL2
  summary: "(CDT) Header files for the Linux kernel for use by glibc"
  description: |
        Kernel-headers includes the C header files that specify the interface between
        the Linux kernel and userspace libraries and programs.  The header files
        define structures and constants that are needed for building most standard
        programs and are also needed for rebuilding the glibc package.

extras:
  rpm_name: kernel-headers
