package:
  name: glibc-headers-amzn2-aarch64
  version: 2.26

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/glibc-headers-2.26-39.amzn2.aarch64.rpm
    sha256: a89dc81eda7019fede38bea0145459ed744e609188bc3261bfc8f3a937c26633
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/glibc-2.26-39.amzn2.src.rpm
    sha256: 29947b1cc20ab2b58472fbfe2c4c8394d4067876f0d8bc1491ea9ba17f99c12e
    no_hoist: true
    folder: source

build:
  number: 3
  noarch: generic
  rpaths:
    - lib
    - lib64
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
    - kernel-headers-amzn2-aarch64 >=2.2.1
    - kernel-headers-amzn2-aarch64 ==4.14.214
  host:
    - glibc-amzn2-aarch64 ==2.26
    - kernel-headers-amzn2-aarch64 >=2.2.1
    - kernel-headers-amzn2-aarch64 ==4.14.214
  run:
    - glibc-amzn2-aarch64 ==2.26
    - kernel-headers-amzn2-aarch64 >=2.2.1
    - kernel-headers-amzn2-aarch64 ==4.14.214

about:
  home: http://www.gnu.org/software/glibc/
  license: LGPLv2+ and LGPLv2+ with exceptions and GPLv2+
  license_family: GPL2
  summary: "(CDT) Header files for development using standard C libraries."
  description: |
        The glibc-headers package contains the header files necessary for developing
        programs which use the standard C libraries (which are used by nearly all
        programs).  If you are developing programs which will use the standard C
        libraries, your system needs to have these standard header files available in
        order to create the executables.  Install glibc-headers if you are going to
        develop programs which will use the standard C libraries.

extras:
  rpm_name: glibc-headers
