package:
  name: libidl-devel-amzn2-aarch64
  version: 0.8.14

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/libIDL-devel-0.8.14-8.amzn2.0.2.aarch64.rpm
    sha256: 82ee705b3adbe79876f33d82959b1fa976b953fc7a740ebdcbeb4f90f65012de
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/libIDL-0.8.14-8.amzn2.0.2.src.rpm
    sha256: 50eb575b0cda48718d8f9f35d3689cb0c65715c21b4fa415c6dca53c2225365a
    no_hoist: true
    folder: source

build:
  number: 3
  noarch: generic
  rpaths:
    - lib
    - lib64
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glib2-devel-amzn2-aarch64 >=2.0
    - info-amzn2-aarch64 ==5.1
    - libidl-amzn2-aarch64 ==0.8.14
    - pkgconfig-amzn2-aarch64 >=0.8
  host:
    - glib2-devel-amzn2-aarch64 >=2.0
    - info-amzn2-aarch64 ==5.1
    - libidl-amzn2-aarch64 ==0.8.14
    - pkgconfig-amzn2-aarch64 >=0.8
  run:
    - glib2-devel-amzn2-aarch64 >=2.0
    - info-amzn2-aarch64 ==5.1
    - libidl-amzn2-aarch64 ==0.8.14
    - pkgconfig-amzn2-aarch64 >=0.8

about:
  home: http://ftp.gnome.org/pub/gnome/sources/libIDL/0.8/
  license: LGPL (>= 2)
  license_family: LGPL
  summary: "(CDT) Development libraries and header files for libIDL"
  description: |
        libIDL is a library for parsing IDL (Interface Definition Language). It can be
        used for both COM-style and CORBA-style IDL.  This package contains the header
        files and libraries needed to write or compile programs that use libIDL.

extras:
  rpm_name: libIDL-devel
