package:
  name: libuuid-devel-amzn2-aarch64
  version: 2.30.2

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/libuuid-devel-2.30.2-2.amzn2.0.4.aarch64.rpm
    sha256: 86b401b67058ff959f70188c0ef02a357d6ee1c5dbbee68f132079b45554c564
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/util-linux-2.30.2-2.amzn2.0.4.src.rpm
    sha256: 7967325dfd44cdb0fd0caa45b27d56da920dd3110a5989c3ae52364b44ae7d82
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libuuid-amzn2-aarch64 ==2.30.2
    - pkgconfig-amzn2-aarch64 ==0.27.1
  host:
    - libuuid-amzn2-aarch64 ==2.30.2
    - pkgconfig-amzn2-aarch64 ==0.27.1
  run:
    - libuuid-amzn2-aarch64 ==2.30.2
    - pkgconfig-amzn2-aarch64 ==0.27.1

about:
  home: http://en.wikipedia.org/wiki/Util-linux
  license: BSD
  license_family: BSD
  summary: "(CDT) Universally unique ID library"
  description: |
        This is the universally unique ID development library and headers, part of
        util-linux.  The libuuid library generates and parses 128-bit universally
        unique id's (UUID's).  A UUID is an identifier that is unique across both
        space and time, with respect to the space of all UUIDs.  A UUID can be used
        for multiple purposes, from tagging objects with an extremely short lifetime,
        to reliably identifying very persistent objects across a network.  See also
        the "uuid-devel" package, which is a separate implementation.

extras:
  rpm_name: libuuid-devel
