package:
  name: libxscrnsaver-amzn2-aarch64
  version: 1.2.2

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/libXScrnSaver-1.2.2-6.1.amzn2.0.2.aarch64.rpm
    sha256: 23724ccc20b6481f096455e62892f0136ae199da8f2a2bae43d5e126fe443255
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/libXScrnSaver-1.2.2-6.1.amzn2.0.2.src.rpm
    sha256: 9ed31bd127b9f45ca3ecfc5cf36c72195a816fbc9beb9ff5c06ad28011959504
    no_hoist: true
    folder: source

build:
  number: 3
  noarch: generic
  rpaths:
    - lib
    - lib64
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
    - libx11-amzn2-aarch64 ==1.6.7
    - libxext-amzn2-aarch64 ==1.3.3
  host:
    - glibc-amzn2-aarch64 ==2.26
    - libx11-amzn2-aarch64 ==1.6.7
    - libxext-amzn2-aarch64 ==1.3.3
  run:
    - glibc-amzn2-aarch64 ==2.26
    - libx11-amzn2-aarch64 ==1.6.7
    - libxext-amzn2-aarch64 ==1.3.3

about:
  home: http://www.x.org
  license: MIT
  license_family: MIT
  summary: "(CDT) X.Org X11 libXss runtime library"
  description: |
        X.Org X11 libXss runtime library

extras:
  rpm_name: libXScrnSaver
