package:
  name: rubygem-io-console-amzn2-aarch64
  version: 0.4.2

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/rubygem-io-console-0.4.2-36.amzn2.0.1.aarch64.rpm
    sha256: 65f53c09f09c9ada4f4f82b59796a69bd1661857c9f8b5280f14cf44222c536c
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/ruby-2.0.0.648-36.amzn2.0.1.src.rpm
    sha256: 119f0f5dcc68a7d4d9cab0e8d8330f4715d64b866318037b0ea1c452ce49fc9e
    no_hoist: true
    folder: source

build:
  number: 3
  noarch: generic
  rpaths:
    - lib
    - lib64
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
    - libcrypt-amzn2-aarch64 ==2.26
    - ruby-libs-amzn2-aarch64 ==2.0.0.648
  host:
    - glibc-amzn2-aarch64 ==2.26
    - libcrypt-amzn2-aarch64 ==2.26
    - ruby-libs-amzn2-aarch64 ==2.0.0.648
  run:
    - glibc-amzn2-aarch64 ==2.26
    - libcrypt-amzn2-aarch64 ==2.26
    - ruby-libs-amzn2-aarch64 ==2.0.0.648

about:
  home: http://ruby-lang.org/
  license: (Ruby or BSD) and Public Domain
  license_family: BSD
  summary: "(CDT) IO/Console is a simple console utilizing library"
  description: |
        IO/Console provides very simple and portable access to console. It doesn't
        provide higher layer features, such like curses and readline.

extras:
  rpm_name: rubygem-io-console
