package:
  name: gdbm-amzn2-aarch64
  version: 1.13

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/gdbm-1.13-6.amzn2.0.2.aarch64.rpm
    sha256: 57d1ec2e23481314ab876ea759df58f8616b52eff9fc08ff58369115a6075ccd
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/gdbm-1.13-6.amzn2.0.2.src.rpm
    sha256: e2866f1817e24bcd350768bf85c8bbddde135513ced29ce315df75f311cf77cf
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
    - ncurses-libs-amzn2-aarch64 ==6.0
    - readline-amzn2-aarch64 ==6.2
  host:
    - glibc-amzn2-aarch64 ==2.26
    - ncurses-libs-amzn2-aarch64 ==6.0
    - readline-amzn2-aarch64 ==6.2
  run:
    - glibc-amzn2-aarch64 ==2.26
    - ncurses-libs-amzn2-aarch64 ==6.0
    - readline-amzn2-aarch64 ==6.2

about:
  home: http://www.gnu.org/software/gdbm/
  license: GPLv3+
  license_family: GPL3
  summary: "(CDT) A GNU set of database routines which use extensible hashing"
  description: |
        Gdbm is a GNU database indexing library, including routines which use
        extensible hashing.  Gdbm works in a similar way to standard UNIX dbm
        routines.  Gdbm is useful for developers who write C applications and need
        access to a simple and efficient database or who are building C applications
        which will use such a database.  If you're a C developer and your programs
        need access to simple database routines, you should install gdbm.  You'll also
        need to install gdbm-devel.

extras:
  rpm_name: gdbm
