package:
  name: cryptsetup-libs-amzn2-aarch64
  version: 1.7.4

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/cryptsetup-libs-1.7.4-4.amzn2.aarch64.rpm
    sha256: 08fbb3a38ccda172851eb907815b6399dbe3078c74d84b8ed406edddd4e7fe24
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/cryptsetup-1.7.4-4.amzn2.src.rpm
    sha256: ad16b6f4596e77afa5ae62a92ff619786518ab11b2a6644d0ee53a146b10b021
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - device-mapper-libs-amzn2-aarch64 ==1.02.146
    - glibc-amzn2-aarch64 ==2.26
    - libgcrypt-amzn2-aarch64 ==1.5.3
    - libgcrypt-amzn2-aarch64 >=1.5.3
    - libgpg-error-amzn2-aarch64 ==1.12
    - libuuid-amzn2-aarch64 ==2.30.2
  host:
    - device-mapper-libs-amzn2-aarch64 ==1.02.146
    - glibc-amzn2-aarch64 ==2.26
    - libgcrypt-amzn2-aarch64 ==1.5.3
    - libgcrypt-amzn2-aarch64 >=1.5.3
    - libgpg-error-amzn2-aarch64 ==1.12
    - libuuid-amzn2-aarch64 ==2.30.2
  run:
    - device-mapper-libs-amzn2-aarch64 ==1.02.146
    - glibc-amzn2-aarch64 ==2.26
    - libgcrypt-amzn2-aarch64 ==1.5.3
    - libgcrypt-amzn2-aarch64 >=1.5.3
    - libgpg-error-amzn2-aarch64 ==1.12
    - libuuid-amzn2-aarch64 ==2.30.2

about:
  home: https://gitlab.com/cryptsetup/cryptsetup
  license: GPLv2+ and LGPLv2+
  license_family: GPL2
  summary: "(CDT) Cryptsetup shared library"
  description: |
        This package contains the cryptsetup shared library, libcryptsetup.

extras:
  rpm_name: cryptsetup-libs
