package:
  name: curl-amzn2-aarch64
  version: 7.61.1

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/curl-7.61.1-12.amzn2.0.2.aarch64.rpm
    sha256: dccf86c541fc033b2ea06853ddba4a2dec561c4b0d180a26bf4223677c256607
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/curl-7.61.1-12.amzn2.0.2.src.rpm
    sha256: fb75b5678cc9ceacbece78025cb0cbb9a44b0e924ae8853cdc4777604ebdba0d
    no_hoist: true
    folder: source

build:
  number: 3
  noarch: generic
  rpaths:
    - lib
    - lib64
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
    - libcurl-amzn2-aarch64 ==7.61.1
    - libmetalink-amzn2-aarch64 ==0.1.3
    - openssl-libs-amzn2-aarch64 ==1.0.2k
    - zlib-amzn2-aarch64 ==1.2.7
  host:
    - glibc-amzn2-aarch64 ==2.26
    - libcurl-amzn2-aarch64 ==7.61.1
    - libmetalink-amzn2-aarch64 ==0.1.3
    - openssl-libs-amzn2-aarch64 ==1.0.2k
    - zlib-amzn2-aarch64 ==1.2.7
  run:
    - glibc-amzn2-aarch64 ==2.26
    - libcurl-amzn2-aarch64 ==7.61.1
    - libmetalink-amzn2-aarch64 ==0.1.3
    - openssl-libs-amzn2-aarch64 ==1.0.2k
    - zlib-amzn2-aarch64 ==1.2.7

about:
  home: https://curl.haxx.se/
  license: MIT
  license_family: MIT
  summary: "(CDT) A utility for getting files from remote servers (FTP, HTTP, and others)"
  description: |
        curl is a command line tool for transferring data with URL syntax, supporting
        FTP, FTPS, HTTP, HTTPS, SCP, SFTP, TFTP, TELNET, DICT, LDAP, LDAPS, FILE,
        IMAP, SMTP, POP3 and RTSP.  curl supports SSL certificates, HTTP POST, HTTP
        PUT, FTP uploading, HTTP form based upload, proxies, cookies, user+password
        authentication (Basic, Digest, NTLM, Negotiate, kerberos...), file transfer
        resume, proxy tunneling and a busload of other useful tricks.

extras:
  rpm_name: curl
