package:
  name: libice-amzn2-aarch64
  version: 1.0.9

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/libICE-1.0.9-9.amzn2.0.2.aarch64.rpm
    sha256: 0935472c1b6572897fe62cb537605185244cd8e3d2fdab6fc05c315a15a892d1
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/libICE-1.0.9-9.amzn2.0.2.src.rpm
    sha256: 9991a3e969ad170fa2d2632fd8f86d6dc1cd053b43e3cf8fb0e19b1f7d598045
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
  host:
    - glibc-amzn2-aarch64 ==2.26
  run:
    - glibc-amzn2-aarch64 ==2.26

about:
  home: http://www.x.org
  license: MIT
  license_family: MIT
  summary: "(CDT) X.Org X11 ICE runtime library"
  description: |
        The X.Org X11 ICE (Inter-Client Exchange) runtime library.

extras:
  rpm_name: libICE
