package:
  name: nss-tools-amzn2-aarch64
  version: 3.53.1

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/nss-tools-3.53.1-3.amzn2.aarch64.rpm
    sha256: 23987cc48a24fa4fc18b89f33c2d331703ed06d37320139aca5c93b703b48f12
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/nss-3.53.1-3.amzn2.src.rpm
    sha256: d7aaefe2f0b7813c966d9014f78af25dc5244cceee6909f79731c4d997edcc28
    no_hoist: true
    folder: source

build:
  number: 3
  noarch: generic
  rpaths:
    - lib
    - lib64
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
    - nspr-amzn2-aarch64 ==4.25.0
    - nss-amzn2-aarch64 ==3.53.1
    - nss-softokn-amzn2-aarch64 ==3.53.1
    - nss-util-amzn2-aarch64 ==3.53.1
    - zlib-amzn2-aarch64 ==1.2.7
  host:
    - glibc-amzn2-aarch64 ==2.26
    - nspr-amzn2-aarch64 ==4.25.0
    - nss-amzn2-aarch64 ==3.53.1
    - nss-softokn-amzn2-aarch64 ==3.53.1
    - nss-util-amzn2-aarch64 ==3.53.1
    - zlib-amzn2-aarch64 ==1.2.7
  run:
    - glibc-amzn2-aarch64 ==2.26
    - nspr-amzn2-aarch64 ==4.25.0
    - nss-amzn2-aarch64 ==3.53.1
    - nss-softokn-amzn2-aarch64 ==3.53.1
    - nss-util-amzn2-aarch64 ==3.53.1
    - zlib-amzn2-aarch64 ==1.2.7

about:
  home: http://www.mozilla.org/projects/security/pki/nss/
  license: MPLv2.0
  license_family: Other
  summary: "(CDT) Tools for the Network Security Services"
  description: |
        Network Security Services (NSS) is a set of libraries designed to support
        cross-platform development of security-enabled client and server applications.
        Applications built with NSS can support SSL v2 and v3, TLS, PKCS #5, PKCS #7,
        PKCS #11, PKCS #12, S/MIME, X.509 v3 certificates, and other security
        standards.  Install the nss-tools package if you need command-line tools to
        manipulate the NSS certificate and key database.

extras:
  rpm_name: nss-tools
