package:
  name: ustr-amzn2-aarch64
  version: 1.0.4

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/ustr-1.0.4-16.amzn2.0.3.aarch64.rpm
    sha256: 891815983f1da5cb689ffe2dba6dc77b9fa35f48815774ba1ff999fc64daf634
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/ustr-1.0.4-16.amzn2.0.3.src.rpm
    sha256: 7477de946dfcd9c18a323e3fbf55abf8fe1137be0adb7d0c114c610963e4210e
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
  host:
    - glibc-amzn2-aarch64 ==2.26
  run:
    - glibc-amzn2-aarch64 ==2.26

about:
  home: http://www.and.org/ustr/
  license: MIT or LGPLv2+ or BSD
  license_family: LGPL
  summary: "(CDT) String library, very low memory overhead, simple to import"
  description: |
        Micro string library, very low overhead from plain strdup() (Ave. 44% for
        0-20B strings). Very easy to use in existing C code. At it's simplest you can
        just include a single header file into your .c and start using it.  This
        package also distributes pre-built shared libraries.

extras:
  rpm_name: ustr
