package:
  name: libxscrnsaver-devel-amzn2-aarch64
  version: 1.2.2

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/libXScrnSaver-devel-1.2.2-6.1.amzn2.0.2.aarch64.rpm
    sha256: cecaff437afd1c135b1d6fe810c5238639fe4d16cc35811a65b946816fce6058
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/libXScrnSaver-1.2.2-6.1.amzn2.0.2.src.rpm
    sha256: 9ed31bd127b9f45ca3ecfc5cf36c72195a816fbc9beb9ff5c06ad28011959504
    no_hoist: true
    folder: source

build:
  number: 3
  noarch: generic
  rpaths:
    - lib
    - lib64
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libxscrnsaver-amzn2-aarch64 ==1.2.2
  host:
    - libxscrnsaver-amzn2-aarch64 ==1.2.2
  run:
    - libxscrnsaver-amzn2-aarch64 ==1.2.2

about:
  home: http://www.x.org
  license: MIT
  license_family: MIT
  summary: "(CDT) X.Org X11 libXScrnSaver development package"
  description: |
        X.Org X11 libXss development package

extras:
  rpm_name: libXScrnSaver-devel
