package:
  name: libfontenc-amzn2-aarch64
  version: 1.1.3

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/libfontenc-1.1.3-3.amzn2.0.2.aarch64.rpm
    sha256: 7322f7ea6983e074e2373b64b7533eb7634a60b4f7886f0fbc4c5d2420b8f5c5
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/libfontenc-1.1.3-3.amzn2.0.2.src.rpm
    sha256: b787e1d3dad105f3d6be9f5b08d528ceb2418cb661b54e6bd304febbcee2f77a
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
    - zlib-amzn2-aarch64 ==1.2.7
  host:
    - glibc-amzn2-aarch64 ==2.26
    - zlib-amzn2-aarch64 ==1.2.7
  run:
    - glibc-amzn2-aarch64 ==2.26
    - zlib-amzn2-aarch64 ==1.2.7

about:
  home: http://www.x.org
  license: MIT
  license_family: MIT
  summary: "(CDT) X.Org X11 libfontenc runtime library"
  description: |
        X.Org X11 libfontenc runtime library

extras:
  rpm_name: libfontenc
