package:
  name: nss-sysinit-amzn2-aarch64
  version: 3.53.1

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/nss-sysinit-3.53.1-3.amzn2.aarch64.rpm
    sha256: 869955c48ba9784a68440c8a235a06432153407c5f4bf22883448c5a09abbfc0
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/nss-3.53.1-3.amzn2.src.rpm
    sha256: d7aaefe2f0b7813c966d9014f78af25dc5244cceee6909f79731c4d997edcc28
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - coreutils-amzn2-aarch64 ==8.22
    - glibc-amzn2-aarch64 ==2.26
    - nspr-amzn2-aarch64 ==4.25.0
    - nss-util-amzn2-aarch64 ==3.53.1
    - sed-amzn2-aarch64 ==4.2.2
  host:
    - coreutils-amzn2-aarch64 ==8.22
    - glibc-amzn2-aarch64 ==2.26
    - nspr-amzn2-aarch64 ==4.25.0
    - nss-util-amzn2-aarch64 ==3.53.1
    - sed-amzn2-aarch64 ==4.2.2
  run:
    - coreutils-amzn2-aarch64 ==8.22
    - glibc-amzn2-aarch64 ==2.26
    - nspr-amzn2-aarch64 ==4.25.0
    - nss-util-amzn2-aarch64 ==3.53.1
    - sed-amzn2-aarch64 ==4.2.2

about:
  home: http://www.mozilla.org/projects/security/pki/nss/
  license: MPLv2.0
  license_family: Other
  summary: "(CDT) System NSS Initialization"
  description: |
        Default Operating System module that manages applications loading NSS globally
        on the system. This module loads the system defined PKCS #11 modules for NSS
        and chains with other NSS modules to load any system or user configured
        modules.

extras:
  rpm_name: nss-sysinit
