package:
  name: libxkbfile-amzn2-aarch64
  version: 1.0.9

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/libxkbfile-1.0.9-3.amzn2.0.2.aarch64.rpm
    sha256: 1a0c4d39e4f52b5c53e57f39cb888d0e426d7e33eff4ea63f69dfec0da38bcd1
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/libxkbfile-1.0.9-3.amzn2.0.2.src.rpm
    sha256: 6990e2c32bc7978340b7fbfc6fd7c9c6a0605456e882848cc998d4b367859679
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
    - libx11-amzn2-aarch64 ==1.6.7
  host:
    - glibc-amzn2-aarch64 ==2.26
    - libx11-amzn2-aarch64 ==1.6.7
  run:
    - glibc-amzn2-aarch64 ==2.26
    - libx11-amzn2-aarch64 ==1.6.7

about:
  home: http://www.x.org
  license: MIT
  license_family: MIT
  summary: "(CDT) X.Org X11 libxkbfile runtime library"
  description: |
        X.Org X11 libxkbfile runtime library

extras:
  rpm_name: libxkbfile
