package:
  name: libxinerama-amzn2-aarch64
  version: 1.1.3

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/libXinerama-1.1.3-2.1.amzn2.0.2.aarch64.rpm
    sha256: 064246c06b824cf68fd5d77b7221833ea43893fe704d44c16c0b05d7273e0d26
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/libXinerama-1.1.3-2.1.amzn2.0.2.src.rpm
    sha256: 836444717c95df08ee2aaf82d7a48bcb89247887b26f4dc1ef3582fdf4ea2a0e
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
    - libx11-amzn2-aarch64 >=1.5.99.902
    - libx11-amzn2-aarch64 ==1.6.7
    - libxext-amzn2-aarch64 ==1.3.3
  host:
    - glibc-amzn2-aarch64 ==2.26
    - libx11-amzn2-aarch64 >=1.5.99.902
    - libx11-amzn2-aarch64 ==1.6.7
    - libxext-amzn2-aarch64 ==1.3.3
  run:
    - glibc-amzn2-aarch64 ==2.26
    - libx11-amzn2-aarch64 >=1.5.99.902
    - libx11-amzn2-aarch64 ==1.6.7
    - libxext-amzn2-aarch64 ==1.3.3

about:
  home: http://www.x.org
  license: MIT
  license_family: MIT
  summary: "(CDT) X.Org X11 libXinerama runtime library"
  description: |
        X.Org X11 libXinerama runtime library

extras:
  rpm_name: libXinerama
