package:
  name: kmod-libs-amzn2-aarch64
  version: 25

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/kmod-libs-25-3.amzn2.0.2.aarch64.rpm
    sha256: 50913689367980d20bd6b506ff2334d2517c4b604ee2d7483e22e6c25646659b
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/kmod-25-3.amzn2.0.2.src.rpm
    sha256: 690f912ad75fa60f2abd7ca91f023009aee784746cce582f74578c80d73059c7
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
    - libgcc-amzn2-aarch64 ==7.3.1
    - xz-libs-amzn2-aarch64 ==5.2.2
    - zlib-amzn2-aarch64 ==1.2.7
  host:
    - glibc-amzn2-aarch64 ==2.26
    - libgcc-amzn2-aarch64 ==7.3.1
    - xz-libs-amzn2-aarch64 ==5.2.2
    - zlib-amzn2-aarch64 ==1.2.7
  run:
    - glibc-amzn2-aarch64 ==2.26
    - libgcc-amzn2-aarch64 ==7.3.1
    - xz-libs-amzn2-aarch64 ==5.2.2
    - zlib-amzn2-aarch64 ==1.2.7

about:
  home: http://git.kernel.org/?p=utils/kernel/kmod/kmod.git;a=summary
  license: LGPL (>= 2)
  license_family: LGPL
  summary: "(CDT) Libraries to handle kernel module loading and unloading"
  description: |
        The kmod-libs package provides runtime libraries for any application that
        wishes to load or unload Linux kernel modules from the running system.

extras:
  rpm_name: kmod-libs
