package:
  name: ncurses-libs-amzn2-aarch64
  version: 6.0

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/ncurses-libs-6.0-8.20170212.amzn2.1.3.aarch64.rpm
    sha256: 56a470c48cf4662f2b9e849c88cc97e2e323e9ac2f5e022ebcb89843aa7dae28
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/ncurses-6.0-8.20170212.amzn2.1.3.src.rpm
    sha256: a0ab33ecd508ea556f1874e5baa8cc751466cf7b37d6f42ef15adcdf4fa4ad8e
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
    - ncurses-base-amzn2-aarch64 ==6.0
  host:
    - glibc-amzn2-aarch64 ==2.26
    - ncurses-base-amzn2-aarch64 ==6.0
  run:
    - glibc-amzn2-aarch64 ==2.26
    - ncurses-base-amzn2-aarch64 ==6.0

about:
  home: http://invisible-island.net/ncurses/ncurses.html
  license: MIT
  license_family: MIT
  summary: "(CDT) Ncurses libraries"
  description: |
        The curses library routines are a terminal-independent method of updating
        character screens with reasonable optimization.  The ncurses (new curses)
        library is a freely distributable replacement for the discontinued 4.4 BSD
        classic curses library.  This package contains the ncurses libraries.

extras:
  rpm_name: ncurses-libs
