package:
  name: at-spi-devel-amzn2-aarch64
  version: 1.32.0

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/at-spi-devel-1.32.0-12.amzn2.0.2.aarch64.rpm
    sha256: e36b9249df409e0ee1adc0e189def177776d92c1bc0c73afaba0fb5a40a2d763
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/at-spi-1.32.0-12.amzn2.0.2.src.rpm
    sha256: f0ba061edc5e1cef0f91a4f62d695b513c181c02a46cf8c7eda98dae99023417
    no_hoist: true
    folder: source

build:
  number: 3
  noarch: generic
  rpaths:
    - lib
    - lib64
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - at-spi-amzn2-aarch64 ==1.32.0
    - atk-devel-amzn2-aarch64 >=1.29.2
    - gtk2-devel-amzn2-aarch64 >=2.10.0
    - gtk2-devel-amzn2-aarch64 >=2.24.31
    - libbonobo-devel-amzn2-aarch64 >=2.4.0
    - orbit2-devel-amzn2-aarch64 >=2.6.0
    - pkgconfig-amzn2-aarch64 ==0.27.1
  host:
    - at-spi-amzn2-aarch64 ==1.32.0
    - atk-devel-amzn2-aarch64 >=1.29.2
    - gtk2-devel-amzn2-aarch64 >=2.10.0
    - gtk2-devel-amzn2-aarch64 >=2.24.31
    - libbonobo-devel-amzn2-aarch64 >=2.4.0
    - orbit2-devel-amzn2-aarch64 >=2.6.0
    - pkgconfig-amzn2-aarch64 ==0.27.1
  run:
    - at-spi-amzn2-aarch64 ==1.32.0
    - atk-devel-amzn2-aarch64 >=1.29.2
    - gtk2-devel-amzn2-aarch64 >=2.10.0
    - gtk2-devel-amzn2-aarch64 >=2.24.31
    - libbonobo-devel-amzn2-aarch64 >=2.4.0
    - orbit2-devel-amzn2-aarch64 >=2.6.0
    - pkgconfig-amzn2-aarch64 ==0.27.1

about:
  home: http://developer.gnome.org/projects/gap/
  license: LGPL (>= 2)
  license_family: LGPL
  summary: "(CDT) Development files for at-spi"
  description: |
        This package contains libraries, header files and developer documentation
        needed for developing applications that interact directly with at-spi.

extras:
  rpm_name: at-spi-devel
