package:
  name: pciutils-devel-amzn2-aarch64
  version: 3.5.1

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/pciutils-devel-3.5.1-3.amzn2.aarch64.rpm
    sha256: 8cb67292a855bfae5a979e5e9e5e608d346bb242e70077193b5420cacb502797
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/pciutils-3.5.1-3.amzn2.src.rpm
    sha256: c74a697575c6f79908887edadcfd5f67bb327780d946399134f36760bd76a415
    no_hoist: true
    folder: source

build:
  number: 3
  noarch: generic
  rpaths:
    - lib
    - lib64
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - pciutils-amzn2-aarch64 ==3.5.1
    - pciutils-libs-amzn2-aarch64 ==3.5.1
    - pkgconfig-amzn2-aarch64 ==0.27.1
    - zlib-devel-amzn2-aarch64 ==1.2.7
  host:
    - pciutils-amzn2-aarch64 ==3.5.1
    - pciutils-libs-amzn2-aarch64 ==3.5.1
    - pkgconfig-amzn2-aarch64 ==0.27.1
    - zlib-devel-amzn2-aarch64 ==1.2.7
  run:
    - pciutils-amzn2-aarch64 ==3.5.1
    - pciutils-libs-amzn2-aarch64 ==3.5.1
    - pkgconfig-amzn2-aarch64 ==0.27.1
    - zlib-devel-amzn2-aarch64 ==1.2.7

about:
  home: http://atrey.karlin.mff.cuni.cz/~mj/pciutils.shtml
  license: GPL (>= 2)
  license_family: GPL3
  summary: "(CDT) Linux PCI development library"
  description: |
        This package contains a library for inspecting and setting devices connected
        to the PCI bus.

extras:
  rpm_name: pciutils-devel
