package:
  name: python3-amzn2-aarch64
  version: 3.7.9

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/python3-3.7.9-1.amzn2.0.1.aarch64.rpm
    sha256: 788d6c301f7a03a590683dc53617e7ce8004c6e9e4567767b3346aec437b4e65
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/python3-3.7.9-1.amzn2.0.1.src.rpm
    sha256: 8dfd84a1bc28a5badf27096122829fc5e15439cbb97668f58cef7c221e8a8c3a
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
    - libcrypt-amzn2-aarch64 ==2.26
    - python3-libs-amzn2-aarch64 ==3.7.9
  host:
    - glibc-amzn2-aarch64 ==2.26
    - libcrypt-amzn2-aarch64 ==2.26
    - python3-libs-amzn2-aarch64 ==3.7.9
  run:
    - glibc-amzn2-aarch64 ==2.26
    - libcrypt-amzn2-aarch64 ==2.26
    - python3-libs-amzn2-aarch64 ==3.7.9

about:
  home: https://www.python.org/
  license: Python
  license_family: Other
  summary: "(CDT) Interpreter of the Python programming language"
  description: |
        Python is an accessible, high-level, dynamically typed, interpreted
        programming language, designed with an emphasis on code readability. It
        includes an extensive standard library, and has a vast ecosystem of third-
        party libraries.  The python3 package provides the "python3" executable: the
        reference interpreter for the Python language, version 3. The majority of its
        standard library is provided in the python3-libs package, which should be
        installed automatically along with python3. The remaining parts of the Python
        standard library are broken out into the python3-tkinter and python3-test
        packages, which may need to be installed separately.  Documentation for Python
        is provided in the python3-docs package.  Packages containing additional
        libraries for Python are generally named with the "python3-" prefix.

extras:
  rpm_name: python3
