package:
  name: xcb-util-renderutil-devel-amzn2-aarch64
  version: 0.3.9

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/xcb-util-renderutil-devel-0.3.9-3.amzn2.0.2.aarch64.rpm
    sha256: 800b9dffcc0de7354724d2b4a71f3fb9a785ff9128d4356347fd696d3de3ab44
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/xcb-util-renderutil-0.3.9-3.amzn2.0.2.src.rpm
    sha256: 04235bed2001f57a0e55b6597649233f3f24903fb580233925b9a8a57c253c88
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - xcb-util-renderutil-amzn2-aarch64 ==0.3.9
    - glibc-amzn2-aarch64 ==2.26
  host:
    - xcb-util-renderutil-amzn2-aarch64 ==0.3.9
    - glibc-amzn2-aarch64 ==2.26
  run:
    - xcb-util-renderutil-amzn2-aarch64 ==0.3.9
    - glibc-amzn2-aarch64 ==2.26

about:
  home: http://xcb.freedesktop.org/
  license: MIT
  license_family: MIT
  summary: "(CDT) A C binding to the X11 protocol"
  description: |
        The X protocol C-language Binding (XCB) is a replacement for Xlib featuring a
        small footprint, latency hiding, direct access to the protocol, improved
        threading support, and extensibility.

extras:
  rpm_name: libxcb
