package:
  name: libogg-amzn2-aarch64
  version: 1.3.0

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/libogg-1.3.0-7.amzn2.0.2.aarch64.rpm
    sha256: a2eea88150cd374221e1d32fb3d4181e1881be2079f6996839f2e230ef4b946a
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/libogg-1.3.0-7.amzn2.0.2.src.rpm
    sha256: 23719d811b94ce2bfbae3f30cda6cb1cc83e98da55532ec1732ebc36771b4e96
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
  host:
    - glibc-amzn2-aarch64 ==2.26
  run:
    - glibc-amzn2-aarch64 ==2.26

about:
  home: http://www.xiph.org/
  license: BSD
  license_family: BSD
  summary: "(CDT) The Ogg bitstream file format library"
  description: |
        Libogg is a library for manipulating Ogg bitstream file formats. Libogg
        supports both making Ogg bitstreams and getting packets from Ogg bitstreams.

extras:
  rpm_name: libogg
