package:
  name: perl-time-hires-amzn2-aarch64
  version: 1.9725

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/perl-Time-HiRes-1.9725-3.amzn2.0.2.aarch64.rpm
    sha256: 6fa147af4051a705cb8fb2f4b1ae0d85adb0754316f2ba7c185f51e1f5556a36
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/perl-Time-HiRes-1.9725-3.amzn2.0.2.src.rpm
    sha256: 44d7b16eaa4278950a34f5e1c2331502f9bee3226c33bb8aefa3a06a01b4706b
    no_hoist: true
    folder: source

build:
  number: 3
  noarch: generic
  rpaths:
    - lib
    - lib64
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
    - perl-amzn2-aarch64 ==5.16.3
    - perl-carp-amzn2-aarch64 ==1.26
    - perl-exporter-amzn2-aarch64 ==5.68
  host:
    - glibc-amzn2-aarch64 ==2.26
    - perl-amzn2-aarch64 ==5.16.3
    - perl-carp-amzn2-aarch64 ==1.26
    - perl-exporter-amzn2-aarch64 ==5.68
  run:
    - glibc-amzn2-aarch64 ==2.26
    - perl-amzn2-aarch64 ==5.16.3
    - perl-carp-amzn2-aarch64 ==1.26
    - perl-exporter-amzn2-aarch64 ==5.68

about:
  home: http://search.cpan.org/dist/Time-HiRes/
  license: GPL+ or Artistic
  license_family: GPL
  summary: "(CDT) High resolution alarm, sleep, gettimeofday, interval timers"
  description: |
        The Time::HiRes module implements a Perl interface to the usleep, nanosleep,
        ualarm, gettimeofday, and setitimer/getitimer system calls, in other words,
        high resolution time and timers.

extras:
  rpm_name: perl-Time-HiRes
