package:
  name: libxxf86vm-amzn2-aarch64
  version: 1.1.4

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/libXxf86vm-1.1.4-1.amzn2.0.2.aarch64.rpm
    sha256: bec38c84c032447c26a6b3b55f526d4d659b084c53a3648465a36f0e6719ce41
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/libXxf86vm-1.1.4-1.amzn2.0.2.src.rpm
    sha256: 5ac15bb34d210b42bd4dec4211d01b972a8a4b7e5632a002e8393dec3fcb43a6
    no_hoist: true
    folder: source

build:
  number: 3
  noarch: generic
  rpaths:
    - lib
    - lib64
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
    - libx11-amzn2-aarch64 >=1.5.99.902
    - libx11-amzn2-aarch64 ==1.6.7
    - libxext-amzn2-aarch64 ==1.3.3
  host:
    - glibc-amzn2-aarch64 ==2.26
    - libx11-amzn2-aarch64 >=1.5.99.902
    - libx11-amzn2-aarch64 ==1.6.7
    - libxext-amzn2-aarch64 ==1.3.3
  run:
    - glibc-amzn2-aarch64 ==2.26
    - libx11-amzn2-aarch64 >=1.5.99.902
    - libx11-amzn2-aarch64 ==1.6.7
    - libxext-amzn2-aarch64 ==1.3.3

about:
  home: http://www.x.org
  license: MIT
  license_family: MIT
  summary: "(CDT) X.Org X11 libXxf86vm runtime library"
  description: |
        X.Org X11 libXxf86vm runtime library

extras:
  rpm_name: libXxf86vm
