package:
  name: cups-devel-amzn2-aarch64
  version: 1.6.3

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/cups-devel-1.6.3-51.amzn2.aarch64.rpm
    sha256: 4e792e313e2ca31c16d306b3bb5f292c4db1b26b785171905284d5ae39e5b13b
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/cups-1.6.3-51.amzn2.src.rpm
    sha256: f81fe4e2a285ce740bf301fe2a47ace7ab9d85aad5ea81d8e171779fa290b7f4
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - cups-libs-amzn2-aarch64 ==1.6.3
    - krb5-devel-amzn2-aarch64 ==1.15.1
    - openssl-devel-amzn2-aarch64 ==1.0.2k
    - zlib-devel-amzn2-aarch64 ==1.2.7
  host:
    - cups-libs-amzn2-aarch64 ==1.6.3
    - krb5-devel-amzn2-aarch64 ==1.15.1
    - openssl-devel-amzn2-aarch64 ==1.0.2k
    - zlib-devel-amzn2-aarch64 ==1.2.7
  run:
    - cups-libs-amzn2-aarch64 ==1.6.3
    - krb5-devel-amzn2-aarch64 ==1.15.1
    - openssl-devel-amzn2-aarch64 ==1.0.2k
    - zlib-devel-amzn2-aarch64 ==1.2.7

about:
  home: http://www.cups.org/
  license: LGPLv2
  license_family: LGPL
  summary: "(CDT) CUPS printing system - development environment"
  description: |
        CUPS printing system provides a portable printing layer for UNIX® operating
        systems. This is the development package for creating additional printer
        drivers, and other CUPS services.

extras:
  rpm_name: cups-devel
