package:
  name: gcc-amzn2-aarch64
  version: 7.3.1

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/gcc-7.3.1-12.amzn2.aarch64.rpm
    sha256: 2b8a4245ed92d7bc0c94e2885d783950dfa5816eeda0e2cb2365badc2e9ee518
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/gcc-7.3.1-12.amzn2.src.rpm
    sha256: f32f053ece942d6fcf5b871bd5cf53634d56977f7c5783d2a026a65ba5394cf5
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - binutils-amzn2-aarch64 >=2.24
    - cpp-amzn2-aarch64 ==7.3.1
    - glibc-amzn2-aarch64 ==2.26
    - glibc-devel-amzn2-aarch64 >=2.2.90
    - gmp-amzn2-aarch64 ==6.0.0
    - libatomic-amzn2-aarch64 ==7.3.1
    - libatomic-amzn2-aarch64 >=7.3.1
    - libgcc-amzn2-aarch64 >=7.3.1
    - libgomp-amzn2-aarch64 ==7.3.1
    - libitm-amzn2-aarch64 ==7.3.1
    - libitm-amzn2-aarch64 >=7.3.1
    - libmpc-amzn2-aarch64 ==1.0.1
    - libsanitizer-amzn2-aarch64 ==7.3.1
    - libsanitizer-amzn2-aarch64 >=7.3.1
    - libsanitizer-amzn2-aarch64 ==7.3.1
    - mpfr-amzn2-aarch64 ==3.1.1
    - zlib-amzn2-aarch64 ==1.2.7
  host:
    - binutils-amzn2-aarch64 >=2.24
    - cpp-amzn2-aarch64 ==7.3.1
    - glibc-amzn2-aarch64 ==2.26
    - glibc-devel-amzn2-aarch64 >=2.2.90
    - gmp-amzn2-aarch64 ==6.0.0
    - libatomic-amzn2-aarch64 ==7.3.1
    - libatomic-amzn2-aarch64 >=7.3.1
    - libgcc-amzn2-aarch64 >=7.3.1
    - libgomp-amzn2-aarch64 ==7.3.1
    - libitm-amzn2-aarch64 ==7.3.1
    - libitm-amzn2-aarch64 >=7.3.1
    - libmpc-amzn2-aarch64 ==1.0.1
    - libsanitizer-amzn2-aarch64 ==7.3.1
    - libsanitizer-amzn2-aarch64 >=7.3.1
    - libsanitizer-amzn2-aarch64 ==7.3.1
    - mpfr-amzn2-aarch64 ==3.1.1
    - zlib-amzn2-aarch64 ==1.2.7
  run:
    - binutils-amzn2-aarch64 >=2.24
    - cpp-amzn2-aarch64 ==7.3.1
    - glibc-amzn2-aarch64 ==2.26
    - glibc-devel-amzn2-aarch64 >=2.2.90
    - gmp-amzn2-aarch64 ==6.0.0
    - libatomic-amzn2-aarch64 ==7.3.1
    - libatomic-amzn2-aarch64 >=7.3.1
    - libgcc-amzn2-aarch64 >=7.3.1
    - libgomp-amzn2-aarch64 ==7.3.1
    - libitm-amzn2-aarch64 ==7.3.1
    - libitm-amzn2-aarch64 >=7.3.1
    - libmpc-amzn2-aarch64 ==1.0.1
    - libsanitizer-amzn2-aarch64 ==7.3.1
    - libsanitizer-amzn2-aarch64 >=7.3.1
    - libsanitizer-amzn2-aarch64 ==7.3.1
    - mpfr-amzn2-aarch64 ==3.1.1
    - zlib-amzn2-aarch64 ==1.2.7

about:
  home: http://gcc.gnu.org
  license: GPLv3+ and GPLv3+ with exceptions and GPLv2+ with exceptions and LGPLv2+ and BSD
  license_family: GPL3
  summary: "(CDT) Various compilers (C, C++, Objective-C, ...)"
  description: |
        The gcc package contains the GNU Compiler Collection version 7. You'll need
        this package in order to compile C code.

extras:
  rpm_name: gcc
