package:
  name: basesystem-amzn2-aarch64
  version: 10.0

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/basesystem-10.0-7.amzn2.0.1.noarch.rpm
    sha256: 3606de0dd19db34715b750b7774a836112d3380d7d2b76b89f3db871c836d8ac
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/basesystem-10.0-7.amzn2.0.1.src.rpm
    sha256: 303ffc769b33bd06f7d3c5d0a1999079ad5afb6d205448dd607a8b6a5cbc3551
    no_hoist: true
    folder: source

build:
  number: 3
  noarch: generic
  rpaths:
    - lib
    - lib64
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - filesystem-amzn2-aarch64 ==3.2
    - setup-amzn2-aarch64 ==2.8.71
  host:
    - filesystem-amzn2-aarch64 ==3.2
    - setup-amzn2-aarch64 ==2.8.71
  run:
    - filesystem-amzn2-aarch64 ==3.2
    - setup-amzn2-aarch64 ==2.8.71

about:
  home: 
  license: Public-Domain
  license_family: Public-Domain
  summary: "(CDT) The skeleton package which defines a simple Amazon Linux system"
  description: |
        Basesystem defines the components of a basic Amazon Linux system (for example,
        the package installation order to use during bootstrapping). Basesystem should
        be in every installation of a system, and it should never be removed.

extras:
  rpm_name: basesystem
