package:
  name: libtasn1-amzn2-aarch64
  version: 4.10

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/libtasn1-4.10-1.amzn2.0.2.aarch64.rpm
    sha256: 6cfda06469314702ad2b225ba1a48463076d218344aeb48fcb693c510911051d
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/libtasn1-4.10-1.amzn2.0.2.src.rpm
    sha256: 99cc7d9be4ecafa389bcb8c2d1d5456b07874ecd6d24e72a73b73a393041043a
    no_hoist: true
    folder: source

build:
  number: 3
  noarch: generic
  rpaths:
    - lib
    - lib64
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
  host:
    - glibc-amzn2-aarch64 ==2.26
  run:
    - glibc-amzn2-aarch64 ==2.26

about:
  home: http://www.gnu.org/software/libtasn1/
  license: GPLv3+ and LGPLv2+
  license_family: GPL3
  summary: "(CDT) The ASN.1 library used in GNUTLS"
  description: |
        A library that provides Abstract Syntax Notation One (ASN.1, as specified by
        the X.680 ITU-T recommendation) parsing and structures management, and
        Distinguished Encoding Rules (DER, as per X.690) encoding and decoding
        functions.

extras:
  rpm_name: libtasn1
