package:
  name: findutils-amzn2-aarch64
  version: 4.5.11

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/findutils-4.5.11-6.amzn2.aarch64.rpm
    sha256: fd1f3f13cac61a7d40c71f2b296057536c105f87681fd26da7fb71185c369583
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/findutils-4.5.11-6.amzn2.src.rpm
    sha256: 8cb38ddd3353da1ca38e2748e4affeb61a422044bf26c05f93cd0e20d83b125d
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
    - libselinux-amzn2-aarch64 ==2.5
  host:
    - glibc-amzn2-aarch64 ==2.26
    - libselinux-amzn2-aarch64 ==2.5
  run:
    - glibc-amzn2-aarch64 ==2.26
    - libselinux-amzn2-aarch64 ==2.5

about:
  home: http://www.gnu.org/software/findutils/
  license: GPLv3+
  license_family: GPL3
  summary: "(CDT) The GNU versions of find utilities (find and xargs)"
  description: |
        The findutils package contains programs which will help you locate files on
        your system.  The find utility searches through a hierarchy of directories
        looking for files which match a certain set of criteria (such as a file name
        pattern).  The xargs utility builds and executes command lines from standard
        input arguments (usually lists of file names generated by the find command).
        You should install findutils because it includes tools that are very useful
        for finding things on your system.

extras:
  rpm_name: findutils
