package:
  name: m4-amzn2-aarch64
  version: 1.4.16

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/m4-1.4.16-10.amzn2.0.2.aarch64.rpm
    sha256: cd95c0f04e835beb4df878b1b8d7b05dfbab05ff6a8820d87462f512fd366019
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/m4-1.4.16-10.amzn2.0.2.src.rpm
    sha256: 3d9f4b06be4e8101cea9af6167025888b01fc4f3f168efbdbbfa0698aaef1c02
    no_hoist: true
    folder: source

build:
  number: 3
  noarch: generic
  rpaths:
    - lib
    - lib64
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
  host:
    - glibc-amzn2-aarch64 ==2.26
  run:
    - glibc-amzn2-aarch64 ==2.26

about:
  home: http://www.gnu.org/software/m4/
  license: GPLv3+
  license_family: GPL3
  summary: "(CDT) The GNU macro processor"
  description: |
        A GNU implementation of the traditional UNIX macro processor.  M4 is useful
        for writing text files which can be logically parsed, and is used by many
        programs as part of their build process.  M4 has built-in functions for
        including files, running shell commands, doing arithmetic, etc.  The autoconf
        program needs m4 for generating configure scripts, but not for running
        configure scripts.  Install m4 if you need a macro processor.

extras:
  rpm_name: m4
