package:
  name: pcre2-amzn2-aarch64
  version: 10.23

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/pcre2-10.23-2.amzn2.0.2.aarch64.rpm
    sha256: 3105477fcb92a5c9c9bd2241ee58517d8179333902358ec5358503c07ae62f03
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/pcre2-10.23-2.amzn2.0.2.src.rpm
    sha256: 36ad98649ff1fcbce2338f49f4ee083b0cc9b2360309d103dce39525e8ae778e
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
  host:
    - glibc-amzn2-aarch64 ==2.26
  run:
    - glibc-amzn2-aarch64 ==2.26

about:
  home: http://www.pcre.org/
  license: BSD
  license_family: BSD
  summary: "(CDT) Perl-compatible regular expression library"
  description: |
        PCRE2 is a re-working of the original PCRE (Perl-compatible regular
        expression) library to provide an entirely new API.  PCRE2 is written in C,
        and it has its own API. There are three sets of functions, one for the 8-bit
        library, which processes strings of bytes, one for the 16-bit library, which
        processes strings of 16-bit values, and one for the 32-bit library, which
        processes strings of 32-bit values. There are no C++ wrappers. This package
        provides support for strings in 8-bit and UTF-8 encodings. Install pcre2-utf16
        or pcre2-utf32 packages for the other ones.  The distribution does contain a
        set of C wrapper functions for the 8-bit library that are based on the POSIX
        regular expression API (see the pcre2posix man page). These can be found in a
        library called libpcre2posix. Note that this just provides a POSIX calling
        interface to PCRE2; the regular expressions themselves still follow Perl
        syntax and semantics. The POSIX API is restricted, and does not give full
        access to all of PCRE2's facilities.

extras:
  rpm_name: pcre2
