package:
  name: fontconfig-amzn2-aarch64
  version: 2.13.0

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/fontconfig-2.13.0-4.3.amzn2.aarch64.rpm
    sha256: 01ddff641585727f86777142cf3361afdd88b10135c5a4fc339b016aea5316d7
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/fontconfig-2.13.0-4.3.amzn2.src.rpm
    sha256: d27fa964cbcbbd78a2cd17349b255f37d6fa44876c0186ffd4b05c63d6aae827
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - coreutils-amzn2-aarch64 ==8.22
    - dejavu-sans-fonts-amzn2-aarch64 ==2.33
    - expat-amzn2-aarch64 ==2.1.0
    - fontpackages-filesystem-amzn2-aarch64 ==1.44
    - freetype-amzn2-aarch64 ==2.8
    - freetype-amzn2-aarch64 >=2.8
    - freetype-amzn2-aarch64 ==2.8
    - glibc-amzn2-aarch64 ==2.26
    - grep-amzn2-aarch64 ==2.20
    - libuuid-amzn2-aarch64 ==2.30.2
  host:
    - coreutils-amzn2-aarch64 ==8.22
    - dejavu-sans-fonts-amzn2-aarch64 ==2.33
    - expat-amzn2-aarch64 ==2.1.0
    - fontpackages-filesystem-amzn2-aarch64 ==1.44
    - freetype-amzn2-aarch64 ==2.8
    - freetype-amzn2-aarch64 >=2.8
    - freetype-amzn2-aarch64 ==2.8
    - glibc-amzn2-aarch64 ==2.26
    - grep-amzn2-aarch64 ==2.20
    - libuuid-amzn2-aarch64 ==2.30.2
  run:
    - coreutils-amzn2-aarch64 ==8.22
    - dejavu-sans-fonts-amzn2-aarch64 ==2.33
    - expat-amzn2-aarch64 ==2.1.0
    - fontpackages-filesystem-amzn2-aarch64 ==1.44
    - freetype-amzn2-aarch64 ==2.8
    - freetype-amzn2-aarch64 >=2.8
    - freetype-amzn2-aarch64 ==2.8
    - glibc-amzn2-aarch64 ==2.26
    - grep-amzn2-aarch64 ==2.20
    - libuuid-amzn2-aarch64 ==2.30.2

about:
  home: http://fontconfig.org
  license: MIT and Public Domain and UCD
  license_family: MIT
  summary: "(CDT) Font configuration and customization library"
  description: |
        Fontconfig is designed to locate fonts within the system and select them
        according to requirements specified by applications.

extras:
  rpm_name: fontconfig
