package:
  name: xz-libs-amzn2-aarch64
  version: 5.2.2

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/xz-libs-5.2.2-1.amzn2.0.2.aarch64.rpm
    sha256: 7c5196e49f1763aceab2a519e2726dc250cb3eef3e2e920961d3bfd94d52cb5a
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/xz-5.2.2-1.amzn2.0.2.src.rpm
    sha256: bcb9c095602e8f3c64b34b19a8487a9b3dffb2160c8a01d81303eb8201bf2069
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
  host:
    - glibc-amzn2-aarch64 ==2.26
  run:
    - glibc-amzn2-aarch64 ==2.26

about:
  home: http://tukaani.org/xz/
  license: LGPL (>= 2)
  license_family: LGPL
  summary: "(CDT) Libraries for decoding LZMA compression"
  description: |
        Libraries for decoding files compressed with LZMA or XZ utils.

extras:
  rpm_name: xz-libs
