package:
  name: libxrandr-amzn2-aarch64
  version: 1.5.1

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/libXrandr-1.5.1-2.amzn2.0.3.aarch64.rpm
    sha256: 0cb8477390b0aeb65b6818f295254e5195d71d29c3f8cd94d0f604f68ed54d60
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/libXrandr-1.5.1-2.amzn2.0.3.src.rpm
    sha256: 7ccd9af12a2893b98af29ca7c2136bd470c2e9f7fd2d9ed9430d83189baf2382
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
    - libx11-amzn2-aarch64 >=1.6.0
    - libx11-amzn2-aarch64 ==1.6.7
    - libxext-amzn2-aarch64 ==1.3.3
    - libxrender-amzn2-aarch64 ==0.9.10
  host:
    - glibc-amzn2-aarch64 ==2.26
    - libx11-amzn2-aarch64 >=1.6.0
    - libx11-amzn2-aarch64 ==1.6.7
    - libxext-amzn2-aarch64 ==1.3.3
    - libxrender-amzn2-aarch64 ==0.9.10
  run:
    - glibc-amzn2-aarch64 ==2.26
    - libx11-amzn2-aarch64 >=1.6.0
    - libx11-amzn2-aarch64 ==1.6.7
    - libxext-amzn2-aarch64 ==1.3.3
    - libxrender-amzn2-aarch64 ==0.9.10

about:
  home: http://www.x.org
  license: MIT
  license_family: MIT
  summary: "(CDT) X.Org X11 libXrandr runtime library"
  description: |
        X.Org X11 libXrandr runtime library

extras:
  rpm_name: libXrandr
