package:
  name: util-linux-amzn2-aarch64
  version: 2.30.2

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/util-linux-2.30.2-2.amzn2.0.4.aarch64.rpm
    sha256: 820e30da6eca55091632bbaafee1f9136a9560d68b982050186418fd175cf379
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/util-linux-2.30.2-2.amzn2.0.4.src.rpm
    sha256: 7967325dfd44cdb0fd0caa45b27d56da920dd3110a5989c3ae52364b44ae7d82
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - audit-libs-amzn2-aarch64 >=1.0.6
    - audit-libs-amzn2-aarch64 ==2.8.1
    - coreutils-amzn2-aarch64 ==8.22
    - glibc-amzn2-aarch64 ==2.26
    - libblkid-amzn2-aarch64 ==2.30.2
    - libcap-ng-amzn2-aarch64 ==0.7.5
    - libcrypt-amzn2-aarch64 ==2.26
    - libfdisk-amzn2-aarch64 ==2.30.2
    - libmount-amzn2-aarch64 ==2.30.2
    - libselinux-amzn2-aarch64 ==2.5
    - libsmartcols-amzn2-aarch64 ==2.30.2
    - libutempter-amzn2-aarch64 ==1.1.6
    - libuuid-amzn2-aarch64 ==2.30.2
    - ncurses-libs-amzn2-aarch64 ==6.0
    - pam-amzn2-aarch64 >=1.1.3
    - pam-amzn2-aarch64 ==1.1.8
    - systemd-libs-amzn2-aarch64 ==219
    - zlib-amzn2-aarch64 ==1.2.7
  host:
    - audit-libs-amzn2-aarch64 >=1.0.6
    - audit-libs-amzn2-aarch64 ==2.8.1
    - coreutils-amzn2-aarch64 ==8.22
    - glibc-amzn2-aarch64 ==2.26
    - libblkid-amzn2-aarch64 ==2.30.2
    - libcap-ng-amzn2-aarch64 ==0.7.5
    - libcrypt-amzn2-aarch64 ==2.26
    - libfdisk-amzn2-aarch64 ==2.30.2
    - libmount-amzn2-aarch64 ==2.30.2
    - libselinux-amzn2-aarch64 ==2.5
    - libsmartcols-amzn2-aarch64 ==2.30.2
    - libutempter-amzn2-aarch64 ==1.1.6
    - libuuid-amzn2-aarch64 ==2.30.2
    - ncurses-libs-amzn2-aarch64 ==6.0
    - pam-amzn2-aarch64 >=1.1.3
    - pam-amzn2-aarch64 ==1.1.8
    - systemd-libs-amzn2-aarch64 ==219
    - zlib-amzn2-aarch64 ==1.2.7
  run:
    - audit-libs-amzn2-aarch64 >=1.0.6
    - audit-libs-amzn2-aarch64 ==2.8.1
    - coreutils-amzn2-aarch64 ==8.22
    - glibc-amzn2-aarch64 ==2.26
    - libblkid-amzn2-aarch64 ==2.30.2
    - libcap-ng-amzn2-aarch64 ==0.7.5
    - libcrypt-amzn2-aarch64 ==2.26
    - libfdisk-amzn2-aarch64 ==2.30.2
    - libmount-amzn2-aarch64 ==2.30.2
    - libselinux-amzn2-aarch64 ==2.5
    - libsmartcols-amzn2-aarch64 ==2.30.2
    - libutempter-amzn2-aarch64 ==1.1.6
    - libuuid-amzn2-aarch64 ==2.30.2
    - ncurses-libs-amzn2-aarch64 ==6.0
    - pam-amzn2-aarch64 >=1.1.3
    - pam-amzn2-aarch64 ==1.1.8
    - systemd-libs-amzn2-aarch64 ==219
    - zlib-amzn2-aarch64 ==1.2.7

about:
  home: http://en.wikipedia.org/wiki/Util-linux
  license: GPLv2 and GPLv2+ and LGPLv2+ and BSD with advertising and Public Domain
  license_family: GPL2
  summary: "(CDT) A collection of basic system utilities"
  description: |
        The util-linux package contains a large variety of low-level system utilities
        that are necessary for a Linux system to function. Among others, Util-linux
        contains the fdisk configuration tool and the login program.

extras:
  rpm_name: util-linux
