package:
  name: libxkbfile-devel-amzn2-aarch64
  version: 1.0.9

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/libxkbfile-devel-1.0.9-3.amzn2.0.2.aarch64.rpm
    sha256: c8ae238143e8486c5cc51a298d9b526dd8eb5693c292c9fe15c3c64098781b58
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/libxkbfile-1.0.9-3.amzn2.0.2.src.rpm
    sha256: 6990e2c32bc7978340b7fbfc6fd7c9c6a0605456e882848cc998d4b367859679
    no_hoist: true
    folder: source

build:
  number: 3
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libxkbfile-amzn2-aarch64 ==1.0.9
  host:
    - libxkbfile-amzn2-aarch64 ==1.0.9
  run:
    - libxkbfile-amzn2-aarch64 ==1.0.9

about:
  home: https://xorg.freedesktop.org/
  license: MIT
  license_family: MIT
  summary: "(CDT) X.Org X11 libxkbfile development package"
  description: libxkbfile is used by the X servers and utilities to parse the XKB configuration data files.

extras:
  rpm_name: libxkbfile-devel
