package:
  name: mesa-libegl-amzn2-aarch64
  version: 18.3.4

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/mesa-libEGL-18.3.4-5.amzn2.0.1.aarch64.rpm
    sha256: 3946230650c0593b0c33ec16664cd842ad64e7a7bba81b96442c9d98f0776669
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/mesa-18.3.4-5.amzn2.0.1.src.rpm
    sha256: 6a8b6b5fe494d93ba576820d4cfa246c67108428b877558a3fbc9c4f2fe9e8af
    no_hoist: true
    folder: source

build:
  number: 3
  noarch: generic
  rpaths:
    - lib
    - lib64
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - expat-amzn2-aarch64 ==2.1.0
    - glibc-amzn2-aarch64 ==2.26
    - libdrm-amzn2-aarch64 ==2.4.97
    - libglvnd-egl-amzn2-aarch64 ==1.0.1
    - libselinux-amzn2-aarch64 ==2.5
    - libwayland-client-amzn2-aarch64 ==1.17.0
    - libwayland-server-amzn2-aarch64 ==1.17.0
    - libx11-amzn2-aarch64 ==1.6.7
    - libxcb-amzn2-aarch64 ==1.12
    - libxshmfence-amzn2-aarch64 ==1.2
    - mesa-libgbm-amzn2-aarch64 ==18.3.4
    - mesa-libglapi-amzn2-aarch64 ==18.3.4
    - zlib-amzn2-aarch64 ==1.2.7
  host:
    - expat-amzn2-aarch64 ==2.1.0
    - glibc-amzn2-aarch64 ==2.26
    - libdrm-amzn2-aarch64 ==2.4.97
    - libglvnd-egl-amzn2-aarch64 ==1.0.1
    - libselinux-amzn2-aarch64 ==2.5
    - libwayland-client-amzn2-aarch64 ==1.17.0
    - libwayland-server-amzn2-aarch64 ==1.17.0
    - libx11-amzn2-aarch64 ==1.6.7
    - libxcb-amzn2-aarch64 ==1.12
    - libxshmfence-amzn2-aarch64 ==1.2
    - mesa-libgbm-amzn2-aarch64 ==18.3.4
    - mesa-libglapi-amzn2-aarch64 ==18.3.4
    - zlib-amzn2-aarch64 ==1.2.7
  run:
    - expat-amzn2-aarch64 ==2.1.0
    - glibc-amzn2-aarch64 ==2.26
    - libdrm-amzn2-aarch64 ==2.4.97
    - libglvnd-egl-amzn2-aarch64 ==1.0.1
    - libselinux-amzn2-aarch64 ==2.5
    - libwayland-client-amzn2-aarch64 ==1.17.0
    - libwayland-server-amzn2-aarch64 ==1.17.0
    - libx11-amzn2-aarch64 ==1.6.7
    - libxcb-amzn2-aarch64 ==1.12
    - libxshmfence-amzn2-aarch64 ==1.2
    - mesa-libgbm-amzn2-aarch64 ==18.3.4
    - mesa-libglapi-amzn2-aarch64 ==18.3.4
    - zlib-amzn2-aarch64 ==1.2.7

about:
  home: http://www.mesa3d.org
  license: MIT
  license_family: MIT
  summary: "(CDT) Mesa libEGL runtime libraries"
  description: |
        Mesa libEGL runtime libraries

extras:
  rpm_name: mesa-libEGL
