package:
  name: bzip2-libs-amzn2-aarch64
  version: 1.0.6

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/bzip2-libs-1.0.6-13.amzn2.0.2.aarch64.rpm
    sha256: 017f62d8a5f8c56b2e3c947c1c6babb552abc73e012d2265c6fde80953f9ddc8
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/bzip2-1.0.6-13.amzn2.0.2.src.rpm
    sha256: d628e30c748a78ba4d69f98730e6030476aeb63f88e8747aa522c48da8eb75ee
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
  host:
    - glibc-amzn2-aarch64 ==2.26
  run:
    - glibc-amzn2-aarch64 ==2.26

about:
  home: http://www.bzip.org/
  license: BSD
  license_family: BSD
  summary: "(CDT) Libraries for applications using bzip2"
  description: |
        Libraries for applications using the bzip2 compression format.

extras:
  rpm_name: bzip2-libs
