package:
  name: xcb-util-amzn2-aarch64
  version: 0.4.0

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/xcb-util-0.4.0-2.amzn2.0.2.aarch64.rpm
    sha256: 26adbae9dd178b46d61ee00c467184e1c782a11a093b007350cefa00f8e26e7b
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/xcb-util-0.4.0-2.amzn2.0.2.src.rpm
    sha256: ae942e6637d0268a5343838259e0f6b65b9e244d90b46ec9687a0628a4bff2bb
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
  host:
    - glibc-amzn2-aarch64 ==2.26
  run:
    - glibc-amzn2-aarch64 ==2.26

about:
  home: http://xcb.freedesktop.org/
  license: MIT
  license_family: MIT
  summary: "(CDT) A C binding to the X11 protocol"
  description: |
        The X protocol C-language Binding (XCB) is a replacement for Xlib featuring a
        small footprint, latency hiding, direct access to the protocol, improved
        threading support, and extensibility.

extras:
  rpm_name: libxcb
