package:
  name: libxtst-amzn2-aarch64
  version: 1.2.3

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/libXtst-1.2.3-1.amzn2.0.2.aarch64.rpm
    sha256: 954fd2ab1f4d33aa9cfeed4409215090936de110c4b102cc8caba0760c186a84
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/libXtst-1.2.3-1.amzn2.0.2.src.rpm
    sha256: 2d06e393a4ffdca4131522f4f5cc03d12be1803ee8ce0a94bf355a29939a6d9a
    no_hoist: true
    folder: source

build:
  number: 3
  noarch: generic
  rpaths:
    - lib
    - lib64
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
    - libx11-amzn2-aarch64 >=1.5.99.902
    - libx11-amzn2-aarch64 ==1.6.7
    - libxext-amzn2-aarch64 ==1.3.3
    - libxi-amzn2-aarch64 ==1.7.9
  host:
    - glibc-amzn2-aarch64 ==2.26
    - libx11-amzn2-aarch64 >=1.5.99.902
    - libx11-amzn2-aarch64 ==1.6.7
    - libxext-amzn2-aarch64 ==1.3.3
    - libxi-amzn2-aarch64 ==1.7.9
  run:
    - glibc-amzn2-aarch64 ==2.26
    - libx11-amzn2-aarch64 >=1.5.99.902
    - libx11-amzn2-aarch64 ==1.6.7
    - libxext-amzn2-aarch64 ==1.3.3
    - libxi-amzn2-aarch64 ==1.7.9

about:
  home: http://www.x.org
  license: MIT
  license_family: MIT
  summary: "(CDT) X.Org X11 libXtst runtime library"
  description: |
        X.Org X11 libXtst runtime library

extras:
  rpm_name: libXtst
