package:
  name: alsa-utils-amzn2-aarch64
  version: 1.1.3

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/alsa-utils-1.1.3-2.amzn2.0.1.aarch64.rpm
    sha256: 627a665381f043ab8fc07bc6abaaedff6c755110d59feca73d120c7866945607
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/alsa-utils-1.1.3-2.amzn2.0.1.src.rpm
    sha256: 597d980fb81ac79813e6ecb851ce6fac0b93a49386fa5885411a0e5b437900a7
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - alsa-lib-amzn2-aarch64 ==1.1.4.1
    - alsa-lib-amzn2-aarch64 >=1.1.4.1
    - glibc-amzn2-aarch64 ==2.26
    - libgcc-amzn2-aarch64 ==7.3.1
    - libsamplerate-amzn2-aarch64 ==0.1.8
    - ncurses-libs-amzn2-aarch64 ==6.0
    - systemd-amzn2-aarch64 >=219
  host:
    - alsa-lib-amzn2-aarch64 ==1.1.4.1
    - alsa-lib-amzn2-aarch64 >=1.1.4.1
    - glibc-amzn2-aarch64 ==2.26
    - libgcc-amzn2-aarch64 ==7.3.1
    - libsamplerate-amzn2-aarch64 ==0.1.8
    - ncurses-libs-amzn2-aarch64 ==6.0
    - systemd-amzn2-aarch64 >=219
  run:
    - alsa-lib-amzn2-aarch64 ==1.1.4.1
    - alsa-lib-amzn2-aarch64 >=1.1.4.1
    - glibc-amzn2-aarch64 ==2.26
    - libgcc-amzn2-aarch64 ==7.3.1
    - libsamplerate-amzn2-aarch64 ==0.1.8
    - ncurses-libs-amzn2-aarch64 ==6.0
    - systemd-amzn2-aarch64 >=219

about:
  home: http://www.alsa-project.org/
  license: GPL (>= 2)
  license_family: GPL3
  summary: "(CDT) Advanced Linux Sound Architecture (ALSA) utilities"
  description: |
        This package contains command line utilities for the Advanced Linux Sound
        Architecture (ALSA).

extras:
  rpm_name: alsa-utils
