package:
  name: rubygem-bigdecimal-amzn2-aarch64
  version: 1.2.0

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/rubygem-bigdecimal-1.2.0-36.amzn2.0.1.aarch64.rpm
    sha256: b60447edaa68848ed42c95a75a23697f9453914ee9e7a45ddb84d62c4e5ad29a
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/ruby-2.0.0.648-36.amzn2.0.1.src.rpm
    sha256: 119f0f5dcc68a7d4d9cab0e8d8330f4715d64b866318037b0ea1c452ce49fc9e
    no_hoist: true
    folder: source

build:
  number: 3
  noarch: generic
  rpaths:
    - lib
    - lib64
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
    - libcrypt-amzn2-aarch64 ==2.26
    - ruby-libs-amzn2-aarch64 ==2.0.0.648
  host:
    - glibc-amzn2-aarch64 ==2.26
    - libcrypt-amzn2-aarch64 ==2.26
    - ruby-libs-amzn2-aarch64 ==2.0.0.648
  run:
    - glibc-amzn2-aarch64 ==2.26
    - libcrypt-amzn2-aarch64 ==2.26
    - ruby-libs-amzn2-aarch64 ==2.0.0.648

about:
  home: http://ruby-lang.org/
  license: GPL+ or Artistic
  license_family: GPL
  summary: "(CDT) BigDecimal provides arbitrary-precision floating point decimal arithmetic"
  description: |
        Ruby provides built-in support for arbitrary precision integer arithmetic. For
        example:  42**13 -> 1265437718438866624512  BigDecimal provides similar
        support for very large or very accurate floating point numbers. Decimal
        arithmetic is also useful for general calculation, because it provides the
        correct answers people expect–whereas normal binary floating point arithmetic
        often introduces subtle errors because of the conversion between base 10 and
        base 2.

extras:
  rpm_name: rubygem-bigdecimal
