package:
  name: harfbuzz-amzn2-aarch64
  version: 1.7.5

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/harfbuzz-1.7.5-2.amzn2.aarch64.rpm
    sha256: 7a265c0d5a19ef6e489876f77210b4861ac91660f5a6f403064ef68287254d18
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/harfbuzz-1.7.5-2.amzn2.src.rpm
    sha256: f9a0e5fe11076e4ac55183fefb62ae7cceec10b0958114c98dbe761d28529a4f
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - freetype-amzn2-aarch64 ==2.8
    - glib2-amzn2-aarch64 ==2.56.1
    - glibc-amzn2-aarch64 ==2.26
    - graphite2-amzn2-aarch64 ==1.3.10
  host:
    - freetype-amzn2-aarch64 ==2.8
    - glib2-amzn2-aarch64 ==2.56.1
    - glibc-amzn2-aarch64 ==2.26
    - graphite2-amzn2-aarch64 ==1.3.10
  run:
    - freetype-amzn2-aarch64 ==2.8
    - glib2-amzn2-aarch64 ==2.56.1
    - glibc-amzn2-aarch64 ==2.26
    - graphite2-amzn2-aarch64 ==1.3.10

about:
  home: http://freedesktop.org/wiki/Software/HarfBuzz
  license: MIT
  license_family: MIT
  summary: "(CDT) Text shaping library"
  description: |
        HarfBuzz is an implementation of the OpenType Layout engine.

extras:
  rpm_name: harfbuzz
