package:
  name: libxdmcp-amzn2-aarch64
  version: 1.1.2

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/libXdmcp-1.1.2-6.amzn2.0.2.aarch64.rpm
    sha256: f3304c703991db895f0018e2c25f91c348a3c7851173412801fc5a08a0dea118
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/libXdmcp-1.1.2-6.amzn2.0.2.src.rpm
    sha256: 850f1cf7a13f049a1c4e94c9bdd9db8b6eccd5f1f3a9f9e965256d25f2beb358
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
  host:
    - glibc-amzn2-aarch64 ==2.26
  run:
    - glibc-amzn2-aarch64 ==2.26

about:
  home: http://www.x.org
  license: MIT
  license_family: MIT
  summary: "(CDT) X Display Manager Control Protocol library"
  description: |
        X Display Manager Control Protocol library.

extras:
  rpm_name: libXdmcp
