package:
  name: pango-amzn2-aarch64
  version: 1.42.4

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/pango-1.42.4-4.amzn2.aarch64.rpm
    sha256: 42aeb1febc08a18f77b75d3a719846bdb8e1bf33acec76c5727cb07f9e394e9d
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/pango-1.42.4-4.amzn2.src.rpm
    sha256: 0b96df84e91b7fa544515ea103a8658d0f1fda806ac02ec748b177876f51615d
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - cairo-amzn2-aarch64 ==1.15.12
    - cairo-amzn2-aarch64 >=1.15.12
    - fontconfig-amzn2-aarch64 ==2.13.0
    - fontconfig-amzn2-aarch64 >=2.13.0
    - freetype-amzn2-aarch64 ==2.8
    - freetype-amzn2-aarch64 >=2.8
    - fribidi-amzn2-aarch64 ==1.0.2
    - fribidi-amzn2-aarch64 >=1.0.2
    - glib2-amzn2-aarch64 ==2.56.1
    - glib2-amzn2-aarch64 >=2.56.1
    - glibc-amzn2-aarch64 ==2.26
    - harfbuzz-amzn2-aarch64 ==1.7.5
    - harfbuzz-amzn2-aarch64 >=1.7.5
    - libthai-amzn2-aarch64 ==0.1.14
    - libthai-amzn2-aarch64 >=0.1.14
    - libx11-amzn2-aarch64 ==1.6.7
    - libxft-amzn2-aarch64 ==2.3.2
    - libxft-amzn2-aarch64 >=2.3.2
    - libxrender-amzn2-aarch64 ==0.9.10
  host:
    - cairo-amzn2-aarch64 ==1.15.12
    - cairo-amzn2-aarch64 >=1.15.12
    - fontconfig-amzn2-aarch64 ==2.13.0
    - fontconfig-amzn2-aarch64 >=2.13.0
    - freetype-amzn2-aarch64 ==2.8
    - freetype-amzn2-aarch64 >=2.8
    - fribidi-amzn2-aarch64 ==1.0.2
    - fribidi-amzn2-aarch64 >=1.0.2
    - glib2-amzn2-aarch64 ==2.56.1
    - glib2-amzn2-aarch64 >=2.56.1
    - glibc-amzn2-aarch64 ==2.26
    - harfbuzz-amzn2-aarch64 ==1.7.5
    - harfbuzz-amzn2-aarch64 >=1.7.5
    - libthai-amzn2-aarch64 ==0.1.14
    - libthai-amzn2-aarch64 >=0.1.14
    - libx11-amzn2-aarch64 ==1.6.7
    - libxft-amzn2-aarch64 ==2.3.2
    - libxft-amzn2-aarch64 >=2.3.2
    - libxrender-amzn2-aarch64 ==0.9.10
  run:
    - cairo-amzn2-aarch64 ==1.15.12
    - cairo-amzn2-aarch64 >=1.15.12
    - fontconfig-amzn2-aarch64 ==2.13.0
    - fontconfig-amzn2-aarch64 >=2.13.0
    - freetype-amzn2-aarch64 ==2.8
    - freetype-amzn2-aarch64 >=2.8
    - fribidi-amzn2-aarch64 ==1.0.2
    - fribidi-amzn2-aarch64 >=1.0.2
    - glib2-amzn2-aarch64 ==2.56.1
    - glib2-amzn2-aarch64 >=2.56.1
    - glibc-amzn2-aarch64 ==2.26
    - harfbuzz-amzn2-aarch64 ==1.7.5
    - harfbuzz-amzn2-aarch64 >=1.7.5
    - libthai-amzn2-aarch64 ==0.1.14
    - libthai-amzn2-aarch64 >=0.1.14
    - libx11-amzn2-aarch64 ==1.6.7
    - libxft-amzn2-aarch64 ==2.3.2
    - libxft-amzn2-aarch64 >=2.3.2
    - libxrender-amzn2-aarch64 ==0.9.10

about:
  home: http://www.pango.org
  license: LGPL (>= 2)
  license_family: LGPL
  summary: "(CDT) System for layout and rendering of internationalized text"
  description: |
        Pango is a library for laying out and rendering of text, with an emphasis on
        internationalization. Pango can be used anywhere that text layout is needed,
        though most of the work on Pango so far has been done in the context of the
        GTK+ widget toolkit. Pango forms the core of text and font handling for GTK+.
        Pango is designed to be modular; the core Pango layout engine can be used with
        different font backends.  The integration of Pango with Cairo provides a
        complete solution with high quality text handling and graphics rendering.

extras:
  rpm_name: pango
