package:
  name: dbus-libs-amzn2-aarch64
  version: 1.10.24

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/dbus-libs-1.10.24-7.amzn2.aarch64.rpm
    sha256: 0e18ffd46a51380e01ceb3ba87d364fb5fd2c53c6696e5d081b2dfe5c9f1a637
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/dbus-1.10.24-7.amzn2.src.rpm
    sha256: 6f65978cb730ebb1be8be1b7aabbaf5069bbacbeb2ad049f3a929cefdcc5f3ea
    no_hoist: true
    folder: source

build:
  number: 3
  noarch: generic
  rpaths:
    - lib
    - lib64
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
    - systemd-libs-amzn2-aarch64 ==219
  host:
    - glibc-amzn2-aarch64 ==2.26
    - systemd-libs-amzn2-aarch64 ==219
  run:
    - glibc-amzn2-aarch64 ==2.26
    - systemd-libs-amzn2-aarch64 ==219

about:
  home: http://www.freedesktop.org/Software/dbus/
  license: (GPLv2+ or AFL) and GPLv2+
  license_family: GPL2
  summary: "(CDT) Libraries for accessing D-BUS"
  description: |
        This package contains lowlevel libraries for accessing D-BUS.

extras:
  rpm_name: dbus-libs
