package:
  name: qrencode-libs-amzn2-aarch64
  version: 3.4.1

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/qrencode-libs-3.4.1-3.amzn2.0.2.aarch64.rpm
    sha256: 85e8092f02f56bdabd4a984e0195ee46e6c44b67890210a31b52e378bfc9c3d2
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/qrencode-3.4.1-3.amzn2.0.2.src.rpm
    sha256: eb3ea431ff21ed04fc3f84c15743285f0c68107fa7630fa8ea9eb8f018de24ca
    no_hoist: true
    folder: source

build:
  number: 3
  noarch: generic
  rpaths:
    - lib
    - lib64
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
  host:
    - glibc-amzn2-aarch64 ==2.26
  run:
    - glibc-amzn2-aarch64 ==2.26

about:
  home: http://megaui.net/fukuchi/works/qrencode/index.en.html
  license: LGPL (>= 2)
  license_family: LGPL
  summary: "(CDT) QR Code encoding library - Shared libraries"
  description: |
        The qrencode-libs package contains the shared libraries and header files for
        applications that use qrencode.

extras:
  rpm_name: qrencode-libs
