package:
  name: git-core-doc-amzn2-aarch64
  version: 2.14.5

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/git-core-doc-2.14.5-1.amzn2.aarch64.rpm
    sha256: 461ee6238159e9c0d9525f3e0b0f2a7af0eee3a34aa61d743e19d870f60a5bf2
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/git-2.14.5-1.amzn2.src.rpm
    sha256: 43534d16b857c3fd7408141a642dac48a7751b6bd9564bcafebc6f3f60d6818b
    no_hoist: true
    folder: source

build:
  number: 3
  noarch: generic
  rpaths:
    - lib
    - lib64
  missing_dso_whitelist:
    - '*'



about:
  home: https://git-scm.com/
  license: GPLv2
  license_family: GPL2
  summary: "(CDT) Documentation files for git-core"
  description: |
        Documentation files for git-core package including man pages.

extras:
  rpm_name: git-core-doc
