package:
  name: libxxf86vm-devel-amzn2-aarch64
  version: 1.1.4

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/libXxf86vm-devel-1.1.4-1.amzn2.0.2.aarch64.rpm
    sha256: 96981d16acaf35ad044ce566cb7490506bafcaaa0b1ca38037731399c69116f7
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/libXxf86vm-1.1.4-1.amzn2.0.2.src.rpm
    sha256: 5ac15bb34d210b42bd4dec4211d01b972a8a4b7e5632a002e8393dec3fcb43a6
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libxxf86vm-amzn2-aarch64 ==1.1.4
  host:
    - libxxf86vm-amzn2-aarch64 ==1.1.4
  run:
    - libxxf86vm-amzn2-aarch64 ==1.1.4

about:
  home: http://www.x.org
  license: MIT
  license_family: MIT
  summary: "(CDT) X.Org X11 libXxf86vm development package"
  description: |
        X.Org X11 libXxf86vm development package

extras:
  rpm_name: libXxf86vm-devel
