package:
  name: libstdcxx-amzn2-aarch64
  version: 7.3.1

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/libstdc%2B%2B-7.3.1-12.amzn2.aarch64.rpm
    sha256: 6e849455ffd3c8e44e6c18bef8def939a6619ea87e7e1342ec73954f00e9a393
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/gcc-7.3.1-12.amzn2.src.rpm
    sha256: f32f053ece942d6fcf5b871bd5cf53634d56977f7c5783d2a026a65ba5394cf5
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 >=2.10.90
    - glibc-amzn2-aarch64 ==2.26
    - libgcc-amzn2-aarch64 ==7.3.1
  host:
    - glibc-amzn2-aarch64 >=2.10.90
    - glibc-amzn2-aarch64 ==2.26
    - libgcc-amzn2-aarch64 ==7.3.1
  run:
    - glibc-amzn2-aarch64 >=2.10.90
    - glibc-amzn2-aarch64 ==2.26
    - libgcc-amzn2-aarch64 ==7.3.1

about:
  home: http://gcc.gnu.org
  license: GPLv3+ and GPLv3+ with exceptions and GPLv2+ with exceptions and LGPLv2+ and BSD
  license_family: GPL3
  summary: "(CDT) GNU Standard C++ Library"
  description: |
        The libstdc++ package contains a rewritten standard compliant GCC Standard C++
        Library.

extras:
  rpm_name: libstdc++
