package:
  name: dejavu-sans-fonts-amzn2-aarch64
  version: 2.33

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/dejavu-sans-fonts-2.33-6.amzn2.noarch.rpm
    sha256: 58fc15022cbff3cd4684174db4a71cb3b5189869c4f8ca6887ac348176a648a3
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/dejavu-fonts-2.33-6.amzn2.src.rpm
    sha256: 2c78ae75ee92a19e0ecbd2d6f1b1e6c343e2c8357057617fb7a03438fcff9ce0
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - dejavu-fonts-common-amzn2-aarch64 ==2.33
  host:
    - dejavu-fonts-common-amzn2-aarch64 ==2.33
  run:
    - dejavu-fonts-common-amzn2-aarch64 ==2.33

about:
  home: http://dejavu-fonts.org/
  license: Bitstream Vera and Public Domain
  license_family: Public-Domain
  summary: "(CDT) Variable-width sans-serif font faces"
  description: |
        The DejaVu font set is based on the “Bitstream Vera” fonts, release 1.10. Its
        purpose is to provide a wider range of characters, while maintaining the
        original style, using an open collaborative development process.  This package
        consists of the DejaVu sans-serif variable-width font faces, in their
        unabridged version.

extras:
  rpm_name: dejavu-sans-fonts
