package:
  name: mesa-khr-devel-amzn2-aarch64
  version: 18.3.4

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/mesa-khr-devel-18.3.4-5.amzn2.0.1.aarch64.rpm
    sha256: da00917c374986e5834b8e704821fc5dae932be1740259ceee0cc0450275b473
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/mesa-18.3.4-5.amzn2.0.1.src.rpm
    sha256: 6a8b6b5fe494d93ba576820d4cfa246c67108428b877558a3fbc9c4f2fe9e8af
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'



about:
  home: http://www.mesa3d.org
  license: MIT
  license_family: MIT
  summary: "(CDT) Mesa Khronos development headers"
  description: |
        Mesa Khronos development headers

extras:
  rpm_name: mesa-khr-devel
