package:
  name: xz-devel-amzn2-aarch64
  version: 5.2.2

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/xz-devel-5.2.2-1.amzn2.0.2.aarch64.rpm
    sha256: e0d521c7dc4cc0d61a92f655d51f642db518288b5ba9c7c961ee7da591190cc6
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/xz-5.2.2-1.amzn2.0.2.src.rpm
    sha256: bcb9c095602e8f3c64b34b19a8487a9b3dffb2160c8a01d81303eb8201bf2069
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - pkgconfig-amzn2-aarch64 ==0.27.1
    - xz-libs-amzn2-aarch64 ==5.2.2
  host:
    - pkgconfig-amzn2-aarch64 ==0.27.1
    - xz-libs-amzn2-aarch64 ==5.2.2
  run:
    - pkgconfig-amzn2-aarch64 ==0.27.1
    - xz-libs-amzn2-aarch64 ==5.2.2

about:
  home: http://tukaani.org/xz/
  license: LGPL (>= 2)
  license_family: LGPL
  summary: "(CDT) Devel libraries & headers for liblzma"
  description: |
        Devel libraries and headers for liblzma.

extras:
  rpm_name: xz-devel
