package:
  name: pixman-amzn2-aarch64
  version: 0.34.0

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/pixman-0.34.0-1.amzn2.0.2.aarch64.rpm
    sha256: ad967ff7edbae814f3068136a61361d75327982183d04bf3563024575ad06bcd
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/pixman-0.34.0-1.amzn2.0.2.src.rpm
    sha256: 7ca6e19d2329b5a85760de2cf8e9792b4d906c07fbaefed31fdb85d0f6ad1c94
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
  host:
    - glibc-amzn2-aarch64 ==2.26
  run:
    - glibc-amzn2-aarch64 ==2.26

about:
  home: http://cgit.freedesktop.org/pixman/
  license: MIT
  license_family: MIT
  summary: "(CDT) Pixel manipulation library"
  description: |
        Pixman is a pixel manipulation library for X and cairo.

extras:
  rpm_name: pixman
