package:
  name: xcb-util-keysyms-amzn2-aarch64
  version: 0.4.0

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/xcb-util-keysyms-0.4.0-1.amzn2.0.2.aarch64.rpm
    sha256: 9fff079617e16d8b347bcbbc1f916d0dd03ceaf8d12a727fb0669062b67b2d82
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/xcb-util-keysyms-0.4.0-1.amzn2.0.2.src.rpm
    sha256: 68a4fbf159a855782cd00bf82506fcdd64b5bc09403f6882cb8d3a72a642d348
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
  host:
    - glibc-amzn2-aarch64 ==2.26
  run:
    - glibc-amzn2-aarch64 ==2.26

about:
  home: http://xcb.freedesktop.org/
  license: MIT
  license_family: MIT
  summary: "(CDT) A C binding to the X11 protocol"
  description: |
        The X protocol C-language Binding (XCB) is a replacement for Xlib featuring a
        small footprint, latency hiding, direct access to the protocol, improved
        threading support, and extensibility.

extras:
  rpm_name: libxcb
