package:
  name: libpng-devel-amzn2-aarch64
  version: 1.5.13

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/libpng-devel-1.5.13-8.amzn2.aarch64.rpm
    sha256: 817a6b095006eb47860c93d2a03b9dbf470b6831e286526fd4c60791e4bb0e2d
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/libpng-1.5.13-8.amzn2.src.rpm
    sha256: 720670090e9da15bd9f60e8f1dc38a55d3663dd2277ed7b27fb7b567a1c39d39
    no_hoist: true
    folder: source

build:
  number: 3
  noarch: generic
  rpaths:
    - lib
    - lib64
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libpng-amzn2-aarch64 ==1.5.13
    - zlib-devel-amzn2-aarch64 ==1.2.7
  host:
    - libpng-amzn2-aarch64 ==1.5.13
    - zlib-devel-amzn2-aarch64 ==1.2.7
  run:
    - libpng-amzn2-aarch64 ==1.5.13
    - zlib-devel-amzn2-aarch64 ==1.2.7

about:
  home: http://www.libpng.org/pub/png/
  license: zlib
  license_family: Other
  summary: "(CDT) Development tools for programs to manipulate PNG image format files"
  description: |
        The libpng-devel package contains header files and documentation necessary for
        developing programs using the PNG (Portable Network Graphics) library.  If you
        want to develop programs which will manipulate PNG image format files, you
        should install libpng-devel.  You'll also need to install the libpng package.

extras:
  rpm_name: libpng-devel
