package:
  name: libxinerama-devel-amzn2-aarch64
  version: 1.1.3

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/libXinerama-devel-1.1.3-2.1.amzn2.0.2.aarch64.rpm
    sha256: bf64abd756796f136787399956462add6aae9fcb6a40dd4e35fe992d3d272112
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/libXinerama-1.1.3-2.1.amzn2.0.2.src.rpm
    sha256: 836444717c95df08ee2aaf82d7a48bcb89247887b26f4dc1ef3582fdf4ea2a0e
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libxinerama-amzn2-aarch64 ==1.1.3
  host:
    - libxinerama-amzn2-aarch64 ==1.1.3
  run:
    - libxinerama-amzn2-aarch64 ==1.1.3

about:
  home: http://www.x.org
  license: MIT
  license_family: MIT
  summary: "(CDT) X.Org X11 libXinerama development package"
  description: |
        X.Org X11 libXinerama development package

extras:
  rpm_name: libXinerama-devel
