package:
  name: libmetalink-amzn2-aarch64
  version: 0.1.3

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/libmetalink-0.1.3-13.amzn2.aarch64.rpm
    sha256: 09c256f41390198ff200f490e45648865895a5b234fb109ac0310e88a6993c4a
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/libmetalink-0.1.3-13.amzn2.src.rpm
    sha256: af0aec2e615d0ff03b96fd674c80f28b00f2d198951b2e418ec80956b87aa389
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - expat-amzn2-aarch64 ==2.1.0
    - glibc-amzn2-aarch64 ==2.26
  host:
    - expat-amzn2-aarch64 ==2.1.0
    - glibc-amzn2-aarch64 ==2.26
  run:
    - expat-amzn2-aarch64 ==2.1.0
    - glibc-amzn2-aarch64 ==2.26

about:
  home: https://launchpad.net/libmetalink
  license: MIT
  license_family: MIT
  summary: "(CDT) Metalink library written in C"
  description: |
        libmetalink is a Metalink C library. It adds Metalink functionality such as
        parsing Metalink XML files to programs written in C.

extras:
  rpm_name: libmetalink
