package:
  name: libxcomposite-devel-amzn2-aarch64
  version: 0.4.4

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/libXcomposite-devel-0.4.4-4.1.amzn2.0.2.aarch64.rpm
    sha256: 90d625d96a090d2945a27a01dce72d3b29975f0ce1997a8e3229f076fe81b767
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/libXcomposite-0.4.4-4.1.amzn2.0.2.src.rpm
    sha256: 3f8406d56c4417defbbe2b3bd16753d76da5ea281ffc5c745183be153e194d44
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libxcomposite-amzn2-aarch64 ==0.4.4
  host:
    - libxcomposite-amzn2-aarch64 ==0.4.4
  run:
    - libxcomposite-amzn2-aarch64 ==0.4.4

about:
  home: http://www.x.org
  license: MIT
  license_family: MIT
  summary: "(CDT) Development files for libXcomposite"
  description: |
        X.Org X11 libXcomposite development package

extras:
  rpm_name: libXcomposite-devel
