package:
  name: libsmartcols-amzn2-aarch64
  version: 2.30.2

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/libsmartcols-2.30.2-2.amzn2.0.4.aarch64.rpm
    sha256: 4f8b88b80f037e04abcc11179a511784afd1b646c3db27b691735ad2688e40f2
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/util-linux-2.30.2-2.amzn2.0.4.src.rpm
    sha256: 7967325dfd44cdb0fd0caa45b27d56da920dd3110a5989c3ae52364b44ae7d82
    no_hoist: true
    folder: source

build:
  number: 3
  noarch: generic
  rpaths:
    - lib
    - lib64
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
  host:
    - glibc-amzn2-aarch64 ==2.26
  run:
    - glibc-amzn2-aarch64 ==2.26

about:
  home: http://en.wikipedia.org/wiki/Util-linux
  license: LGPL (>= 2)
  license_family: LGPL
  summary: "(CDT) Formatting library for ls-like programs."
  description: |
        This is library for ls-like terminal programs, part of util-linux.

extras:
  rpm_name: libsmartcols
