package:
  name: gtkmm24-amzn2-aarch64
  version: 2.24.5

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/gtkmm24-2.24.5-1.amzn2.0.2.aarch64.rpm
    sha256: f229e4a932067d3c2711b405e04e62b34f415cf3e6419024dabf705b45084844
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/gtkmm24-2.24.5-1.amzn2.0.2.src.rpm
    sha256: 646fa4177ca8837e92ee8966c010bb88249dccf5e26a0e5ed5b4cdadf39e0991
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - atk-amzn2-aarch64 ==2.22.0
    - atkmm-amzn2-aarch64 ==2.24.2
    - cairo-amzn2-aarch64 ==1.15.12
    - cairomm-amzn2-aarch64 ==1.12.0
    - fontconfig-amzn2-aarch64 ==2.13.0
    - freetype-amzn2-aarch64 ==2.8
    - gdk-pixbuf2-amzn2-aarch64 ==2.36.12
    - glib2-amzn2-aarch64 ==2.56.1
    - glibc-amzn2-aarch64 ==2.26
    - glibmm24-amzn2-aarch64 ==2.56.0
    - gtk2-amzn2-aarch64 ==2.24.31
    - libgcc-amzn2-aarch64 ==7.3.1
    - libsigcxx20-amzn2-aarch64 ==2.10.0
    - libstdcxx-amzn2-aarch64 ==7.3.1
    - pango-amzn2-aarch64 ==1.42.4
    - pangomm-amzn2-aarch64 ==2.40.1
  host:
    - atk-amzn2-aarch64 ==2.22.0
    - atkmm-amzn2-aarch64 ==2.24.2
    - cairo-amzn2-aarch64 ==1.15.12
    - cairomm-amzn2-aarch64 ==1.12.0
    - fontconfig-amzn2-aarch64 ==2.13.0
    - freetype-amzn2-aarch64 ==2.8
    - gdk-pixbuf2-amzn2-aarch64 ==2.36.12
    - glib2-amzn2-aarch64 ==2.56.1
    - glibc-amzn2-aarch64 ==2.26
    - glibmm24-amzn2-aarch64 ==2.56.0
    - gtk2-amzn2-aarch64 ==2.24.31
    - libgcc-amzn2-aarch64 ==7.3.1
    - libsigcxx20-amzn2-aarch64 ==2.10.0
    - libstdcxx-amzn2-aarch64 ==7.3.1
    - pango-amzn2-aarch64 ==1.42.4
    - pangomm-amzn2-aarch64 ==2.40.1
  run:
    - atk-amzn2-aarch64 ==2.22.0
    - atkmm-amzn2-aarch64 ==2.24.2
    - cairo-amzn2-aarch64 ==1.15.12
    - cairomm-amzn2-aarch64 ==1.12.0
    - fontconfig-amzn2-aarch64 ==2.13.0
    - freetype-amzn2-aarch64 ==2.8
    - gdk-pixbuf2-amzn2-aarch64 ==2.36.12
    - glib2-amzn2-aarch64 ==2.56.1
    - glibc-amzn2-aarch64 ==2.26
    - glibmm24-amzn2-aarch64 ==2.56.0
    - gtk2-amzn2-aarch64 ==2.24.31
    - libgcc-amzn2-aarch64 ==7.3.1
    - libsigcxx20-amzn2-aarch64 ==2.10.0
    - libstdcxx-amzn2-aarch64 ==7.3.1
    - pango-amzn2-aarch64 ==1.42.4
    - pangomm-amzn2-aarch64 ==2.40.1

about:
  home: http://www.gtkmm.org/
  license: LGPL (>= 2)
  license_family: LGPL
  summary: "(CDT) C++ interface for GTK2 (a GUI library for X)"
  description: |
        gtkmm provides a C++ interface to the GTK+ GUI library. gtkmm2 wraps GTK+ 2.
        Highlights include typesafe callbacks, widgets extensible via inheritance and
        a comprehensive set of widget classes that can be freely combined to quickly
        create complex user interfaces.

extras:
  rpm_name: gtkmm24
