package:
  name: tcp_wrappers-libs-amzn2-aarch64
  version: 7.6

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/tcp_wrappers-libs-7.6-77.amzn2.0.2.aarch64.rpm
    sha256: 9c2a9fe0898f21c1b3804a78418b27693fd70dc3084f1c0bbec52b14ef63e616
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/tcp_wrappers-7.6-77.amzn2.0.2.src.rpm
    sha256: 426afe73cd12a26edaa3737c4d8c765ed1a0be8bc88aa48f6d850dd051ff8991
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
  host:
    - glibc-amzn2-aarch64 ==2.26
  run:
    - glibc-amzn2-aarch64 ==2.26

about:
  home: ftp://ftp.porcupine.org/pub/security/index.html
  license: BSD
  license_family: BSD
  summary: "(CDT) Libraries for tcp_wrappers"
  description: |
        tcp_wrappers-libs contains the libraries of the tcp_wrappers package.

extras:
  rpm_name: tcp_wrappers-libs
