package:
  name: libdrm-devel-amzn2-aarch64
  version: 2.4.97

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/libdrm-devel-2.4.97-2.amzn2.aarch64.rpm
    sha256: 188d9215f4dfec063f329e966b107522c475e0aad74b87321ca02579e705af5d
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/libdrm-2.4.97-2.amzn2.src.rpm
    sha256: e4e00152bddaf47cea5b0b5aba356b1d2bf9c56cd69f2ea44d90cc9071bf2ee5
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - kernel-headers-amzn2-aarch64 >=2.6.27
    - libdrm-amzn2-aarch64 ==2.4.97
    - pkgconfig-amzn2-aarch64 ==0.27.1
  host:
    - kernel-headers-amzn2-aarch64 >=2.6.27
    - libdrm-amzn2-aarch64 ==2.4.97
    - pkgconfig-amzn2-aarch64 ==0.27.1
  run:
    - kernel-headers-amzn2-aarch64 >=2.6.27
    - libdrm-amzn2-aarch64 ==2.4.97
    - pkgconfig-amzn2-aarch64 ==0.27.1

about:
  home: http://dri.sourceforge.net
  license: MIT
  license_family: MIT
  summary: "(CDT) Direct Rendering Manager development package"
  description: |
        Direct Rendering Manager development package

extras:
  rpm_name: libdrm-devel
