package:
  name: lz4-amzn2-aarch64
  version: 1.7.5

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/lz4-1.7.5-2.amzn2.0.1.aarch64.rpm
    sha256: 8f32b1f8651586fc94bf092206f73011f95a4c7c350fcdf719f30b36251efae7
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/lz4-1.7.5-2.amzn2.0.1.src.rpm
    sha256: cc7ff37476502126faa384dc7700905c0721f94e9ef7dd606fc5f405a8b1ff7c
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
  host:
    - glibc-amzn2-aarch64 ==2.26
  run:
    - glibc-amzn2-aarch64 ==2.26

about:
  home: https://lz4.github.io/lz4/
  license: GPLv2+ and BSD
  license_family: GPL2
  summary: "(CDT) Extremely fast compression algorithm"
  description: |
        LZ4 is an extremely fast loss-less compression algorithm, providing
        compression speed at 400 MB/s per core, scalable with multi-core CPU. It also
        features an extremely fast decoder, with speed in multiple GB/s per core,
        typically reaching RAM speed limits on multi-core systems.

extras:
  rpm_name: lz4
