package:
  name: perl-getopt-long-amzn2-aarch64
  version: 2.40

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/perl-Getopt-Long-2.40-3.amzn2.noarch.rpm
    sha256: 9bcb4e6201e3bf6e6185faa1ee912fbce2b5b8e8688d68639a5616cc211b8200
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/perl-Getopt-Long-2.40-3.amzn2.src.rpm
    sha256: 6ec100098b7293d10a4d3bd1ee9eda2b86980f35dc01bd021c56e403ed5b3be6
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - perl-amzn2-aarch64 >=5.004
    - perl-amzn2-aarch64 ==5.16.3
    - perl-constant-amzn2-aarch64 ==1.27
    - perl-exporter-amzn2-aarch64 ==5.68
    - perl-pod-usage-amzn2-aarch64 >=1.63
    - perl-text-parsewords-amzn2-aarch64 ==3.29
  host:
    - perl-amzn2-aarch64 >=5.004
    - perl-amzn2-aarch64 ==5.16.3
    - perl-constant-amzn2-aarch64 ==1.27
    - perl-exporter-amzn2-aarch64 ==5.68
    - perl-pod-usage-amzn2-aarch64 >=1.63
    - perl-text-parsewords-amzn2-aarch64 ==3.29
  run:
    - perl-amzn2-aarch64 >=5.004
    - perl-amzn2-aarch64 ==5.16.3
    - perl-constant-amzn2-aarch64 ==1.27
    - perl-exporter-amzn2-aarch64 ==5.68
    - perl-pod-usage-amzn2-aarch64 >=1.63
    - perl-text-parsewords-amzn2-aarch64 ==3.29

about:
  home: http://search.cpan.org/dist/Getopt-Long/
  license: GPLv2+ or Artistic
  license_family: GPL2
  summary: "(CDT) Extended processing of command line options"
  description: |
        The Getopt::Long module implements an extended getopt function called
        GetOptions(). It parses the command line from @ARGV, recognizing and removing
        specified options and their possible values.  It adheres to the POSIX syntax
        for command line options, with GNU extensions. In general, this means that
        options have long names instead of single letters, and are introduced with a
        double dash "--". Support for bundling of command line options, as was the
        case with the more traditional single-letter approach, is provided but not
        enabled by default.

extras:
  rpm_name: perl-Getopt-Long
