package:
  name: pciutils-libs-amzn2-aarch64
  version: 3.5.1

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/pciutils-libs-3.5.1-3.amzn2.aarch64.rpm
    sha256: 91ab916caafdda493c920c51991ddd1c5d3ed26dbd66520a3ad21c6a3a9e4584
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/pciutils-3.5.1-3.amzn2.src.rpm
    sha256: c74a697575c6f79908887edadcfd5f67bb327780d946399134f36760bd76a415
    no_hoist: true
    folder: source

build:
  number: 3
  noarch: generic
  rpaths:
    - lib
    - lib64
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
  host:
    - glibc-amzn2-aarch64 ==2.26
  run:
    - glibc-amzn2-aarch64 ==2.26

about:
  home: http://atrey.karlin.mff.cuni.cz/~mj/pciutils.shtml
  license: GPL (>= 2)
  license_family: GPL3
  summary: "(CDT) Linux PCI library"
  description: |
        This package contains a library for inspecting and setting devices connected
        to the PCI bus.

extras:
  rpm_name: pciutils-libs
