package:
  name: cairo-devel-amzn2-aarch64
  version: 1.15.12

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/cairo-devel-1.15.12-4.amzn2.aarch64.rpm
    sha256: f0daad166f9e43ea01fc0ce533df4b53bf3bb405eeac8c60da39e87f9bf6362e
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/cairo-1.15.12-4.amzn2.src.rpm
    sha256: 5869d8f350de3814301df557e5d6587577ddc6cea5a9e28eafce8e6132663e9d
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - cairo-amzn2-aarch64 ==1.15.12
  host:
    - cairo-amzn2-aarch64 ==1.15.12
  run:
    - cairo-amzn2-aarch64 ==1.15.12

about:
  home: http://cairographics.org
  license: LGPLv2 or MPLv1.1
  license_family: LGPL
  summary: "(CDT) Development files for cairo"
  description: |
        Cairo is a 2D graphics library designed to provide high-quality display and
        print output.  This package contains libraries, header files and developer
        documentation needed for developing software which uses the cairo graphics
        library.

extras:
  rpm_name: cairo-devel
