package:
  name: libxrender-devel-amzn2-aarch64
  version: 0.9.10

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/libXrender-devel-0.9.10-1.amzn2.0.2.aarch64.rpm
    sha256: 01a6246c58e93765c2205fff5129bdc5f28d19136a1badedf6f2d17c166ef75e
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/libXrender-0.9.10-1.amzn2.0.2.src.rpm
    sha256: 2fe1544bf29659492949c6cd05b8bbfa96b6dab548d5e3e013176dd7dda02f44
    no_hoist: true
    folder: source

build:
  number: 3
  noarch: generic
  rpaths:
    - lib
    - lib64
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libxrender-amzn2-aarch64 ==0.9.10
  host:
    - libxrender-amzn2-aarch64 ==0.9.10
  run:
    - libxrender-amzn2-aarch64 ==0.9.10

about:
  home: http://www.x.org
  license: MIT
  license_family: MIT
  summary: "(CDT) X.Org X11 libXrender development package"
  description: |
        X.Org X11 libXrender development package

extras:
  rpm_name: libXrender-devel
