package:
  name: libsndfile-amzn2-aarch64
  version: 1.0.25

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/libsndfile-1.0.25-12.amzn2.aarch64.rpm
    sha256: 66f8eb90d61a8ad8f470b77ec522ebc09a5b5bbfe1d72fb90bfbd1c1f92f76d6
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/libsndfile-1.0.25-12.amzn2.src.rpm
    sha256: c029eaffccaf264cb840b0649739ededeb553819ca0bfa2b793749b5812dab4f
    no_hoist: true
    folder: source

build:
  number: 3
  noarch: generic
  rpaths:
    - lib
    - lib64
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - flac-libs-amzn2-aarch64 ==1.3.0
    - glibc-amzn2-aarch64 ==2.26
    - gsm-amzn2-aarch64 ==1.0.13
    - libogg-amzn2-aarch64 ==1.3.0
    - libvorbis-amzn2-aarch64 ==1.3.3
  host:
    - flac-libs-amzn2-aarch64 ==1.3.0
    - glibc-amzn2-aarch64 ==2.26
    - gsm-amzn2-aarch64 ==1.0.13
    - libogg-amzn2-aarch64 ==1.3.0
    - libvorbis-amzn2-aarch64 ==1.3.3
  run:
    - flac-libs-amzn2-aarch64 ==1.3.0
    - glibc-amzn2-aarch64 ==2.26
    - gsm-amzn2-aarch64 ==1.0.13
    - libogg-amzn2-aarch64 ==1.3.0
    - libvorbis-amzn2-aarch64 ==1.3.3

about:
  home: http://www.mega-nerd.com/libsndfile/
  license: LGPLv2+ and GPLv2+ and BSD
  license_family: GPL2
  summary: "(CDT) Library for reading and writing sound files"
  description: |
        libsndfile is a C library for reading and writing sound files such as AIFF,
        AU, WAV, and others through one standard interface. It can currently
        read/write 8, 16, 24 and 32-bit PCM files as well as 32 and 64-bit floating
        point WAV files and a number of compressed formats. It compiles and runs on
        *nix, MacOS, and Win32.

extras:
  rpm_name: libsndfile
