package:
  name: libxcursor-devel-amzn2-aarch64
  version: 1.1.15

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/libXcursor-devel-1.1.15-1.amzn2.aarch64.rpm
    sha256: e52de2a1277e7063f7034f309a5936b289dd98a24f0ecafc1eeb60468de0b0cb
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/libXcursor-1.1.15-1.amzn2.src.rpm
    sha256: 24e11c92b3f0611a6e1a601d38116e49adc9dd7c81a9bf670623f2b0dea949dc
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libxcursor-amzn2-aarch64 ==1.1.15
  host:
    - libxcursor-amzn2-aarch64 ==1.1.15
  run:
    - libxcursor-amzn2-aarch64 ==1.1.15

about:
  home: https://www.x.org
  license: MIT
  license_family: MIT
  summary: "(CDT) Development files for libXcursor"
  description: |
        libXcursor development package.

extras:
  rpm_name: libXcursor-devel
