package:
  name: libgomp-amzn2-aarch64
  version: 7.3.1

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/libgomp-7.3.1-12.amzn2.aarch64.rpm
    sha256: 29acef48ea7a94e5d0b746953069a44ca4523aa74d8995f0918b3cda11885611
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/gcc-7.3.1-12.amzn2.src.rpm
    sha256: f32f053ece942d6fcf5b871bd5cf53634d56977f7c5783d2a026a65ba5394cf5
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
  host:
    - glibc-amzn2-aarch64 ==2.26
  run:
    - glibc-amzn2-aarch64 ==2.26

about:
  home: http://gcc.gnu.org
  license: GPLv3+ and GPLv3+ with exceptions and GPLv2+ with exceptions and LGPLv2+ and BSD
  license_family: GPL3
  summary: "(CDT) GCC OpenMP v4.5 shared support library"
  description: |
        This package contains GCC shared support library which is needed for OpenMP
        v4.5 support.

extras:
  rpm_name: libgomp
