package:
  name: python3-pip-amzn2-aarch64
  version: 9.0.3

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/python3-pip-9.0.3-1.amzn2.0.2.noarch.rpm
    sha256: e777c2142bdb68966303030dede169fe75371bab5ed873dbc50816aee24df871
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/python-pip-9.0.3-1.amzn2.0.2.src.rpm
    sha256: 53cd2751d0fb2bb5fb67da0faa131d6d223ba7826c203cfd9b21c43a579db712
    no_hoist: true
    folder: source

build:
  number: 3
  noarch: generic
  rpaths:
    - lib
    - lib64
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - python3-amzn2-aarch64 ==3.7.9
    - python3-setuptools-amzn2-aarch64 ==38.4.0
  host:
    - python3-amzn2-aarch64 ==3.7.9
    - python3-setuptools-amzn2-aarch64 ==38.4.0
  run:
    - python3-amzn2-aarch64 ==3.7.9
    - python3-setuptools-amzn2-aarch64 ==38.4.0

about:
  home: http://www.pip-installer.org
  license: MIT
  license_family: MIT
  summary: "(CDT) A tool for installing and managing Python3 packages"
  description: |
        pip is a package management system used to install and manage software
        packages written in Python. Many packages can be found in the Python Package
        Index (PyPI). pip is a recursive acronym that can stand for either "Pip
        Installs Packages" or "Pip Installs Python".

extras:
  rpm_name: python3-pip
