package:
  name: libcrypt-amzn2-aarch64
  version: 2.26

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/libcrypt-2.26-39.amzn2.aarch64.rpm
    sha256: ea71214990064231d01ac4c1a3b8cea818f5f88b0e155c62fbc24f8ea3913fcf
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/glibc-2.26-39.amzn2.src.rpm
    sha256: 29947b1cc20ab2b58472fbfe2c4c8394d4067876f0d8bc1491ea9ba17f99c12e
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
  host:
    - glibc-amzn2-aarch64 ==2.26
  run:
    - glibc-amzn2-aarch64 ==2.26

about:
  home: http://www.gnu.org/software/glibc/
  license: LGPLv2+ and LGPLv2+ with exceptions and GPLv2+
  license_family: GPL2
  summary: "(CDT) Password hashing library (non-NSS version)"
  description: |
        This package provides the crypt function, which implements password hashing.
        The glibc implementation of the cryptographic algorithms is used by this
        package.

extras:
  rpm_name: libcrypt
