package:
  name: cairo-amzn2-aarch64
  version: 1.15.12

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/cairo-1.15.12-4.amzn2.aarch64.rpm
    sha256: f81b9d1099bf33afbedc0e8a7a47d9d4adfcbfde093e76774297b3de6cf18036
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/cairo-1.15.12-4.amzn2.src.rpm
    sha256: 5869d8f350de3814301df557e5d6587577ddc6cea5a9e28eafce8e6132663e9d
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - fontconfig-amzn2-aarch64 ==2.13.0
    - freetype-amzn2-aarch64 ==2.8
    - glib2-amzn2-aarch64 ==2.56.1
    - glibc-amzn2-aarch64 ==2.26
    - libglvnd-egl-amzn2-aarch64 ==1.0.1
    - libglvnd-glx-amzn2-aarch64 ==1.0.1
    - libpng-amzn2-aarch64 ==1.5.13
    - libx11-amzn2-aarch64 ==1.6.7
    - libxcb-amzn2-aarch64 ==1.12
    - libxext-amzn2-aarch64 ==1.3.3
    - libxrender-amzn2-aarch64 ==0.9.10
    - pixman-amzn2-aarch64 ==0.34.0
    - zlib-amzn2-aarch64 ==1.2.7
  host:
    - fontconfig-amzn2-aarch64 ==2.13.0
    - freetype-amzn2-aarch64 ==2.8
    - glib2-amzn2-aarch64 ==2.56.1
    - glibc-amzn2-aarch64 ==2.26
    - libglvnd-egl-amzn2-aarch64 ==1.0.1
    - libglvnd-glx-amzn2-aarch64 ==1.0.1
    - libpng-amzn2-aarch64 ==1.5.13
    - libx11-amzn2-aarch64 ==1.6.7
    - libxcb-amzn2-aarch64 ==1.12
    - libxext-amzn2-aarch64 ==1.3.3
    - libxrender-amzn2-aarch64 ==0.9.10
    - pixman-amzn2-aarch64 ==0.34.0
    - zlib-amzn2-aarch64 ==1.2.7
  run:
    - fontconfig-amzn2-aarch64 ==2.13.0
    - freetype-amzn2-aarch64 ==2.8
    - glib2-amzn2-aarch64 ==2.56.1
    - glibc-amzn2-aarch64 ==2.26
    - libglvnd-egl-amzn2-aarch64 ==1.0.1
    - libglvnd-glx-amzn2-aarch64 ==1.0.1
    - libpng-amzn2-aarch64 ==1.5.13
    - libx11-amzn2-aarch64 ==1.6.7
    - libxcb-amzn2-aarch64 ==1.12
    - libxext-amzn2-aarch64 ==1.3.3
    - libxrender-amzn2-aarch64 ==0.9.10
    - pixman-amzn2-aarch64 ==0.34.0
    - zlib-amzn2-aarch64 ==1.2.7

about:
  home: http://cairographics.org
  license: LGPLv2 or MPLv1.1
  license_family: LGPL
  summary: "(CDT) A 2D graphics library"
  description: |
        Cairo is a 2D graphics library designed to provide high-quality display and
        print output. Currently supported output targets include the X Window System,
        in-memory image buffers, and image files (PDF, PostScript, and SVG).  Cairo is
        designed to produce consistent output on all output media while taking
        advantage of display hardware acceleration when available.

extras:
  rpm_name: cairo
