package:
  name: libxshmfence-amzn2-aarch64
  version: 1.2

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/libxshmfence-1.2-1.amzn2.0.2.aarch64.rpm
    sha256: 1e8e02d6713fcfaf86d0da4bb88f661699b00592c0160c7ed419891082671436
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/libxshmfence-1.2-1.amzn2.0.2.src.rpm
    sha256: b80a9f3e65914e3f00d8176667cdc2e7d577820d7ca57ba74828dbfdb01d1eed
    no_hoist: true
    folder: source

build:
  number: 5
  noarch: generic

  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
  host:
    - glibc-amzn2-aarch64 ==2.26
  run:
    - glibc-amzn2-aarch64 ==2.26

about:
  home: http://www.x.org/
  license: MIT
  license_family: MIT
  summary: "(CDT) X11 shared memory fences"
  description: |
        Shared memory fences for X11, as used in DRI3.

extras:
  rpm_name: libxshmfence
