package:
  name: libglvnd-gles-amzn2-aarch64
  version: 1.0.1

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/libglvnd-gles-1.0.1-0.1.git5baa1e5.amzn2.0.1.aarch64.rpm
    sha256: 74fd491c172c56a8c3b53e4601b4a401e86676c3471a42e9beb9ce25b6eef832
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/libglvnd-1.0.1-0.1.git5baa1e5.amzn2.0.1.src.rpm
    sha256: 8de516b03b41124fda9642b96b8bea7cf60604c31ffd82c4a6e93e9cb9b3b765
    no_hoist: true
    folder: source

build:
  number: 3
  noarch: generic
  rpaths:
    - lib
    - lib64
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - glibc-amzn2-aarch64 ==2.26
    - libglvnd-amzn2-aarch64 ==1.0.1
    - mesa-libegl-amzn2-aarch64 >=18.3.4
  host:
    - glibc-amzn2-aarch64 ==2.26
    - libglvnd-amzn2-aarch64 ==1.0.1
    - mesa-libegl-amzn2-aarch64 >=18.3.4
  run:
    - glibc-amzn2-aarch64 ==2.26
    - libglvnd-amzn2-aarch64 ==1.0.1
    - mesa-libegl-amzn2-aarch64 >=18.3.4

about:
  home: https://github.com/NVIDIA/libglvnd
  license: MIT
  license_family: MIT
  summary: "(CDT) GLES support for libglvnd"
  description: |
        libGLESv[12] are the common dispatch interface for the GLES API.

extras:
  rpm_name: libglvnd-gles
