package:
  name: openssh-amzn2-aarch64
  version: 7.4p1

source:
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core/openssh-7.4p1-21.amzn2.0.1.aarch64.rpm
    sha256: 440cee85d493188f1bb5b2c66f6ac4719431fefbf8fc43cc31cb7d6b26a0ac2c
    no_hoist: true
    folder: binary
  - url: https://graviton-rpms.s3.amazonaws.com/amzn2-core-source_2021_01_26/amzn2-core-source/openssh-7.4p1-21.amzn2.0.1.src.rpm
    sha256: 6e07f6e54529c297b39c4721296281355a3148223fb92819f05ff6f3898d7514
    no_hoist: true
    folder: source

build:
  number: 3
  noarch: generic
  rpaths:
    - lib
    - lib64
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - audit-libs-amzn2-aarch64 >=1.0.8
    - fipscheck-lib-amzn2-aarch64 ==1.4.1
    - glibc-amzn2-aarch64 ==2.26
    - libcrypt-amzn2-aarch64 ==2.26
    - libselinux-amzn2-aarch64 >=1.27.7
    - openldap-amzn2-aarch64 ==2.4.44
    - openssl-libs-amzn2-aarch64 ==1.0.2k
    - zlib-amzn2-aarch64 ==1.2.7
  host:
    - audit-libs-amzn2-aarch64 >=1.0.8
    - fipscheck-lib-amzn2-aarch64 ==1.4.1
    - glibc-amzn2-aarch64 ==2.26
    - libcrypt-amzn2-aarch64 ==2.26
    - libselinux-amzn2-aarch64 >=1.27.7
    - openldap-amzn2-aarch64 ==2.4.44
    - openssl-libs-amzn2-aarch64 ==1.0.2k
    - zlib-amzn2-aarch64 ==1.2.7
  run:
    - audit-libs-amzn2-aarch64 >=1.0.8
    - fipscheck-lib-amzn2-aarch64 ==1.4.1
    - glibc-amzn2-aarch64 ==2.26
    - libcrypt-amzn2-aarch64 ==2.26
    - libselinux-amzn2-aarch64 >=1.27.7
    - openldap-amzn2-aarch64 ==2.4.44
    - openssl-libs-amzn2-aarch64 ==1.0.2k
    - zlib-amzn2-aarch64 ==1.2.7

about:
  home: http://www.openssh.com/portable.html
  license: BSD
  license_family: BSD
  summary: "(CDT) An open source implementation of SSH protocol versions 1 and 2"
  description: |
        SSH (Secure SHell) is a program for logging into and executing commands on a
        remote machine. SSH is intended to replace rlogin and rsh, and to provide
        secure encrypted communications between two untrusted hosts over an insecure
        network. X11 connections and arbitrary TCP/IP ports can also be forwarded over
        the secure channel.  OpenSSH is OpenBSD's version of the last free version of
        SSH, bringing it up to date in terms of security and features.  This package
        includes the core files necessary for both the OpenSSH client and server. To
        make this package useful, you should also install openssh-clients, openssh-
        server, or both.

extras:
  rpm_name: openssh
